// bulk_upload_questions_batch1.dart
//
// HOW TO USE:
// 1. Copy this file into your Flutter project (e.g. lib/scripts/bulk_upload_questions_batch1.dart)
// 2. Temporarily call `await bulkUploadQuestionsBatch1();` from somewhere that runs once
//    — easiest is a temporary button on HomeScreen, or right after Firebase.initializeApp()
//    in main.dart (run once, then REMOVE the call so it doesn't re-run and duplicate data).
// 3. Run the app once, confirm in Firebase Console that `questions` collection is populated.
// 4. Remove the button/call so random users can't re-trigger it.
//
// This is BATCH 1 of several — 180 questions (30 per category).
// Ask for Batch 2, 3, etc. to keep adding more toward 1000 total.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

Future<void> bulkUploadQuestionsBatch1() async {
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  final collection = firestore.collection('questions');

  for (final q in _batch1Questions) {
    final docRef = collection.doc(); // auto-generated ID
    batch.set(docRef, q);
  }

  try {
    await batch.commit();
    debugPrint('✅ Uploaded ${_batch1Questions.length} questions (Batch 1)');
  } catch (e) {
    debugPrint('❌ Bulk upload failed: $e');
  }
}

final List<Map<String, dynamic>> _batch1Questions = [
  // ================= GENERAL (30) =================
  {
    'category': 'General',
    'question': 'What is the capital of India?',
    'options': ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many days are there in a leap year?',
    'options': ['364', '365', '366', '367'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the currency of Japan?',
    'options': ['Won', 'Yuan', 'Yen', 'Ringgit'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which is the largest ocean on Earth?',
    'options': ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    'correctAnswerIndex': 3,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many colors are there in a rainbow?',
    'options': ['5', '6', '7', '8'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the national animal of India?',
    'options': ['Lion', 'Elephant', 'Tiger', 'Peacock'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which language has the most native speakers worldwide?',
    'options': ['English', 'Mandarin Chinese', 'Hindi', 'Spanish'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the tallest mountain in the world?',
    'options': ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many continents are there on Earth?',
    'options': ['5', '6', '7', '8'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the smallest country in the world by area?',
    'options': ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which fruit is known as the "King of Fruits"?',
    'options': ['Mango', 'Durian', 'Jackfruit', 'Pineapple'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the largest desert in the world?',
    'options': ['Sahara', 'Gobi', 'Antarctic', 'Arabian'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'How many time zones does Russia span?',
    'options': ['7', '9', '11', '13'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What is the official language of Brazil?',
    'options': ['Spanish', 'Portuguese', 'French', 'Italian'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which metal is liquid at room temperature?',
    'options': ['Lead', 'Mercury', 'Zinc', 'Tin'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What does "www" stand for?',
    'options': [
      'World Wide Web',
      'World Web Wide',
      'Wide World Web',
      'Web World Wide',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which country gifted the Statue of Liberty to the USA?',
    'options': ['England', 'Spain', 'France', 'Italy'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the hardest natural substance on Earth?',
    'options': ['Gold', 'Iron', 'Diamond', 'Platinum'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many bones are there in the adult human body?',
    'options': ['186', '206', '226', '246'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which country is known as the "Land of the Rising Sun"?',
    'options': ['China', 'South Korea', 'Japan', 'Thailand'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the capital of Australia?',
    'options': ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which is the longest river in the world?',
    'options': ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the main ingredient in traditional hummus?',
    'options': ['Lentils', 'Chickpeas', 'Black beans', 'Kidney beans'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'How many strings does a standard violin have?',
    'options': ['3', '4', '5', '6'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which is the smallest planet in our solar system?',
    'options': ['Mars', 'Venus', 'Mercury', 'Pluto'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the national sport of Japan?',
    'options': ['Judo', 'Karate', 'Sumo wrestling', 'Kendo'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which continent is the Sahara Desert located in?',
    'options': ['Asia', 'Africa', 'Australia', 'South America'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'What is the most spoken language in the world by total speakers (including second language)?',
    'options': ['Mandarin', 'Spanish', 'English', 'Hindi'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'Which everyday item was originally called a "Kodak"?',
    'options': ['Telephone', 'Camera', 'Typewriter', 'Radio'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What is the freezing point of water in Celsius?',
    'options': ['-10°C', '0°C', '10°C', '32°C'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },

  // ================= SCIENCE (30) =================
  {
    'category': 'Science',
    'question': 'What is the chemical symbol for water?',
    'options': ['H2O', 'CO2', 'NaCl', 'HCl'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the largest organ in the human body?',
    'options': ['Liver', 'Brain', 'Skin', 'Heart'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What planet is known as the Red Planet?',
    'options': ['Venus', 'Jupiter', 'Mars', 'Saturn'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What gas do plants absorb from the atmosphere?',
    'options': ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the powerhouse of the cell?',
    'options': ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the speed of light in a vacuum (approx)?',
    'options': ['300,000 km/s', '150,000 km/s', '3,000 km/s', '1,000,000 km/s'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which element has the atomic number 1?',
    'options': ['Helium', 'Hydrogen', 'Oxygen', 'Carbon'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the process by which plants make food called?',
    'options': ['Respiration', 'Photosynthesis', 'Transpiration', 'Digestion'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'How many chambers does the human heart have?',
    'options': ['2', '3', '4', '5'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What type of blood cells fight infection?',
    'options': [
      'Red blood cells',
      'White blood cells',
      'Platelets',
      'Plasma cells',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Who developed the theory of general relativity?',
    'options': [
      'Isaac Newton',
      'Albert Einstein',
      'Niels Bohr',
      'Galileo Galilei',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the unit of electrical resistance?',
    'options': ['Volt', 'Watt', 'Ohm', 'Ampere'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which gas makes up about 78% of Earth\'s atmosphere?',
    'options': ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the study of living organisms called?',
    'options': ['Physics', 'Chemistry', 'Biology', 'Geology'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What part of the plant conducts photosynthesis?',
    'options': ['Root', 'Stem', 'Leaf', 'Flower'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the pH value of pure water?',
    'options': ['5', '7', '9', '11'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'Which vitamin is produced when human skin is exposed to sunlight?',
    'options': ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the smallest unit of life?',
    'options': ['Atom', 'Molecule', 'Cell', 'Tissue'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which scientist proposed the laws of motion?',
    'options': [
      'Albert Einstein',
      'Isaac Newton',
      'Galileo Galilei',
      'Nikola Tesla',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the chemical formula for table salt?',
    'options': ['NaCl', 'KCl', 'CaCl2', 'MgCl2'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which planet has the most moons in our solar system?',
    'options': ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What do you call an animal that eats only plants?',
    'options': ['Carnivore', 'Omnivore', 'Herbivore', 'Insectivore'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the boiling point of water at sea level in Celsius?',
    'options': ['90°C', '100°C', '110°C', '120°C'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which organ pumps blood throughout the human body?',
    'options': ['Lungs', 'Liver', 'Heart', 'Kidney'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the study of earthquakes called?',
    'options': ['Seismology', 'Geology', 'Meteorology', 'Volcanology'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which blood type is known as the universal donor?',
    'options': ['A', 'B', 'AB', 'O negative'],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What force keeps planets in orbit around the sun?',
    'options': ['Magnetism', 'Gravity', 'Friction', 'Nuclear force'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the main gas found in the sun?',
    'options': ['Oxygen', 'Helium', 'Hydrogen', 'Nitrogen'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the term for animals that are active at night?',
    'options': ['Diurnal', 'Nocturnal', 'Crepuscular', 'Arboreal'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'How many pairs of chromosomes are in a normal human cell?',
    'options': ['21', '22', '23', '24'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= HISTORY (30) =================
  {
    'category': 'History',
    'question': 'Who wrote the Indian national anthem "Jana Gana Mana"?',
    'options': [
      'Mahatma Gandhi',
      'Rabindranath Tagore',
      'Subhash Chandra Bose',
      'Bankim Chandra Chatterjee',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'In which year did India gain independence?',
    'options': ['1945', '1946', '1947', '1948'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Who was the first Prime Minister of India?',
    'options': [
      'Mahatma Gandhi',
      'Jawaharlal Nehru',
      'Sardar Patel',
      'Dr. Rajendra Prasad',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Which empire built the Taj Mahal?',
    'options': [
      'Maratha Empire',
      'Mughal Empire',
      'Gupta Empire',
      'Chola Empire',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'In which year did World War II end?',
    'options': ['1943', '1944', '1945', '1946'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Who was known as the "Iron Man of India"?',
    'options': [
      'Jawaharlal Nehru',
      'Sardar Vallabhbhai Patel',
      'Subhash Chandra Bose',
      'Bhagat Singh',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which ancient civilization built the pyramids of Giza?',
    'options': ['Mesopotamian', 'Egyptian', 'Roman', 'Greek'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Who was the first President of the United States?',
    'options': [
      'Thomas Jefferson',
      'Abraham Lincoln',
      'George Washington',
      'John Adams',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'The Dandi March led by Gandhi was against which law?',
    'options': [
      'Rowlatt Act',
      'Salt Tax',
      'Partition of Bengal',
      'Jallianwala Bagh',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which wall divided a major European city during the Cold War?',
    'options': ['Great Wall', 'Berlin Wall', 'Hadrian\'s Wall', 'Western Wall'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who founded the Mauryan Empire?',
    'options': ['Ashoka', 'Chandragupta Maurya', 'Bindusara', 'Samudragupta'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'In which year did the Titanic sink?',
    'options': ['1910', '1912', '1914', '1916'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the Roman general known for crossing the Alps with elephants?',
    'options': ['Julius Caesar', 'Hannibal', 'Spartacus', 'Nero'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The Quit India Movement was launched in which year?',
    'options': ['1940', '1942', '1944', '1946'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which country was formerly known as Persia?',
    'options': ['Iraq', 'Iran', 'Syria', 'Turkey'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who is known as the "Father of the Nation" in India?',
    'options': [
      'Jawaharlal Nehru',
      'Subhash Chandra Bose',
      'Mahatma Gandhi',
      'Sardar Patel',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Which war was fought between 1914 and 1918?',
    'options': ['World War I', 'World War II', 'Cold War', 'Vietnam War'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question':
        'Who discovered the sea route to India via the Cape of Good Hope?',
    'options': [
      'Christopher Columbus',
      'Vasco da Gama',
      'Ferdinand Magellan',
      'Marco Polo',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Which Indian freedom fighter formed the Indian National Army (INA)?',
    'options': [
      'Bhagat Singh',
      'Subhash Chandra Bose',
      'Lala Lajpat Rai',
      'Chandrashekhar Azad',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The French Revolution began in which year?',
    'options': ['1776', '1789', '1799', '1804'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the last Mughal emperor of India?',
    'options': ['Akbar', 'Shah Jahan', 'Aurangzeb', 'Bahadur Shah II'],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Which ship carried the Pilgrims to America in 1620?',
    'options': ['Santa Maria', 'Mayflower', 'Endeavour', 'Beagle'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The Battle of Plassey was fought in which year?',
    'options': ['1757', '1857', '1657', '1957'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Who was the first woman Prime Minister of India?',
    'options': [
      'Sonia Gandhi',
      'Indira Gandhi',
      'Pratibha Patil',
      'Sushma Swaraj',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Which empire was ruled by Genghis Khan?',
    'options': [
      'Ottoman Empire',
      'Mongol Empire',
      'Roman Empire',
      'Persian Empire',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'The Great Wall of China was primarily built to defend against invasions from which direction?',
    'options': ['South', 'East', 'North', 'West'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was assassinated in Sarajevo in 1914, triggering World War I?',
    'options': [
      'Kaiser Wilhelm II',
      'Archduke Franz Ferdinand',
      'Tsar Nicholas II',
      'King George V',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Which Indian city was formerly known as Bombay?',
    'options': ['Mumbai', 'Kolkata', 'Chennai', 'Pune'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'The Renaissance period began in which country?',
    'options': ['France', 'Germany', 'Italy', 'Spain'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who led the Salt Satyagraha in 1930?',
    'options': [
      'Jawaharlal Nehru',
      'Mahatma Gandhi',
      'Sardar Patel',
      'Subhash Chandra Bose',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },

  // ================= GEOGRAPHY (30) =================
  {
    'category': 'Geography',
    'question': 'Which is the largest country in the world by area?',
    'options': ['China', 'USA', 'Russia', 'Canada'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which country has the most population in the world?',
    'options': ['China', 'India', 'USA', 'Indonesia'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of France?',
    'options': ['Lyon', 'Marseille', 'Paris', 'Nice'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which river flows through Egypt?',
    'options': ['Amazon', 'Nile', 'Congo', 'Niger'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which is the smallest continent by area?',
    'options': ['Europe', 'Antarctica', 'Australia', 'South America'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Canada?',
    'options': ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which mountain range separates Europe and Asia?',
    'options': ['Alps', 'Andes', 'Ural Mountains', 'Himalayas'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which country is known as the "Land of a Thousand Lakes"?',
    'options': ['Sweden', 'Finland', 'Norway', 'Denmark'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the largest island in the world?',
    'options': ['Madagascar', 'Borneo', 'Greenland', 'New Guinea'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which desert is the largest hot desert in the world?',
    'options': ['Gobi', 'Sahara', 'Kalahari', 'Thar'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian state is known as "God\'s Own Country"?',
    'options': ['Goa', 'Kerala', 'Tamil Nadu', 'Karnataka'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Italy?',
    'options': ['Milan', 'Venice', 'Rome', 'Florence'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which country has the most time zones?',
    'options': ['USA', 'Russia', 'France', 'China'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which is the driest continent on Earth?',
    'options': ['Africa', 'Australia', 'Antarctica', 'Asia'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Mount Kilimanjaro is located in which country?',
    'options': ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which strait separates Europe from Africa?',
    'options': [
      'Bering Strait',
      'Strait of Gibraltar',
      'Bosphorus Strait',
      'Malacca Strait',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the longest mountain range in the world?',
    'options': ['Himalayas', 'Rockies', 'Andes', 'Alps'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country is both in Europe and Asia?',
    'options': ['Russia', 'Turkey', 'Kazakhstan', 'Both Russia and Turkey'],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Spain?',
    'options': ['Barcelona', 'Madrid', 'Valencia', 'Seville'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question':
        'Which sea has the highest salt concentration, making swimmers float easily?',
    'options': ['Red Sea', 'Dead Sea', 'Black Sea', 'Caspian Sea'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country has the most volcanoes?',
    'options': ['Japan', 'Indonesia', 'Iceland', 'Philippines'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Germany?',
    'options': ['Munich', 'Frankfurt', 'Berlin', 'Hamburg'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which river is the longest in India?',
    'options': ['Yamuna', 'Ganges', 'Godavari', 'Brahmaputra'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country does the Amazon Rainforest primarily belong to?',
    'options': ['Peru', 'Colombia', 'Brazil', 'Venezuela'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of South Korea?',
    'options': ['Busan', 'Seoul', 'Incheon', 'Daegu'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which is the highest waterfall in the world?',
    'options': [
      'Niagara Falls',
      'Victoria Falls',
      'Angel Falls',
      'Iguazu Falls',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which country is shaped like a boot?',
    'options': ['Spain', 'Italy', 'Greece', 'Portugal'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Egypt?',
    'options': ['Alexandria', 'Cairo', 'Giza', 'Luxor'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which US state is known as the "Sunshine State"?',
    'options': ['California', 'Florida', 'Texas', 'Arizona'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country has the most natural lakes?',
    'options': ['USA', 'Russia', 'Canada', 'Finland'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= SPORTS (30) =================
  {
    'category': 'Sports',
    'question':
        'How many players are there in a football (soccer) team on the field?',
    'options': ['9', '10', '11', '12'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'In which sport would you perform a "slam dunk"?',
    'options': ['Volleyball', 'Basketball', 'Tennis', 'Badminton'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'How often are the Summer Olympic Games held?',
    'options': [
      'Every 2 years',
      'Every 3 years',
      'Every 4 years',
      'Every 5 years',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which country won the first ever FIFA World Cup in 1930?',
    'options': ['Brazil', 'Argentina', 'Uruguay', 'Italy'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'How many players are on a cricket team?',
    'options': ['9', '10', '11', '12'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which sport uses terms like "love" and "deuce"?',
    'options': ['Badminton', 'Tennis', 'Squash', 'Table Tennis'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Who has won the most Grand Slam titles in men\'s tennis (as of recent years)?',
    'options': [
      'Roger Federer',
      'Rafael Nadal',
      'Novak Djokovic',
      'Andy Murray',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'In which country did the sport of badminton originate?',
    'options': ['China', 'India', 'England', 'Malaysia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'How many rings are there in the Olympic symbol?',
    'options': ['4', '5', '6', '7'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which country has won the most FIFA World Cups?',
    'options': ['Germany', 'Argentina', 'Brazil', 'Italy'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the maximum score possible with three darts in a single throw round (standard darts)?',
    'options': ['120', '160', '180', '200'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'In cricket, what is it called when a bowler takes three wickets in three consecutive balls?',
    'options': ['Century', 'Hat-trick', 'Maiden over', 'Duck'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country hosted the 2016 Summer Olympics?',
    'options': ['China', 'UK', 'Brazil', 'Japan'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'How many holes are there in a standard round of golf?',
    'options': ['9', '12', '18', '21'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which sport is associated with the term "checkmate"?',
    'options': ['Chess', 'Carrom', 'Billiards', 'Bridge'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Who is often referred to as the "God of Cricket" in India?',
    'options': ['Virat Kohli', 'Sachin Tendulkar', 'MS Dhoni', 'Kapil Dev'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'In which sport is the "Ashes" trophy contested?',
    'options': ['Rugby', 'Cricket', 'Football', 'Hockey'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are on a standard volleyball team on the court?',
    'options': ['5', '6', '7', '8'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which country is credited with inventing the sport of table tennis?',
    'options': ['China', 'Japan', 'England', 'Sweden'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What color card is shown to a footballer to send them off the field?',
    'options': ['Yellow', 'Red', 'Blue', 'Orange'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which Grand Slam tennis tournament is played on clay courts?',
    'options': ['Wimbledon', 'US Open', 'French Open', 'Australian Open'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'How many periods are there in an ice hockey game?',
    'options': ['2', '3', '4', '5'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which Indian city hosted the 2010 Commonwealth Games?',
    'options': ['Mumbai', 'New Delhi', 'Bangalore', 'Chennai'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the national sport of India (unofficially most associated)?',
    'options': ['Cricket', 'Field Hockey', 'Kabaddi', 'Football'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'In boxing, how many rounds are there in a professional world championship bout typically?',
    'options': ['8', '10', '12', '15'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which country won the Cricket World Cup in 2011?',
    'options': ['Australia', 'Sri Lanka', 'India', 'South Africa'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'What shape is a standard boxing ring, despite its name?',
    'options': ['Circle', 'Square', 'Octagon', 'Rectangle'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which athlete is known as the fastest man in the world for his 100m sprint records?',
    'options': ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Justin Gatlin'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are on a basketball team on the court at one time?',
    'options': ['4', '5', '6', '7'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'The Wimbledon tennis tournament is held in which country?',
    'options': ['USA', 'France', 'England', 'Australia'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },

  // ================= ENTERTAINMENT (30) =================
  {
    'category': 'Entertainment',
    'question': 'Which company created Mickey Mouse?',
    'options': ['Warner Bros', 'Disney', 'Universal', 'Pixar'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the highest-grossing animated film franchise (as of recent data)?',
    'options': ['Shrek', 'Frozen', 'Toy Story', 'Despicable Me'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Which instrument has 88 keys?',
    'options': ['Guitar', 'Piano', 'Violin', 'Flute'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which streaming platform produced the series "Stranger Things"?',
    'options': ['Amazon Prime', 'Netflix', 'Hulu', 'Disney+'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Who directed the movie "Jurassic Park"?',
    'options': [
      'James Cameron',
      'Steven Spielberg',
      'George Lucas',
      'Christopher Nolan',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which Bollywood actor is known as the "King of Bollywood"?',
    'options': ['Salman Khan', 'Aamir Khan', 'Shah Rukh Khan', 'Akshay Kumar'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional wizarding school in the Harry Potter series?',
    'options': ['Durmstrang', 'Beauxbatons', 'Hogwarts', 'Ilvermorny'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which artist is known as the "King of Pop"?',
    'options': ['Elvis Presley', 'Michael Jackson', 'Prince', 'Elton John'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which Pixar movie features a clownfish searching for his son?',
    'options': ['Finding Nemo', 'Shark Tale', 'Moana', 'Luca'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Who composed the music for most of the "Star Wars" films?',
    'options': ['Hans Zimmer', 'John Williams', 'Danny Elfman', 'James Horner'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian film won the Academy Award for Best Original Song for "Jai Ho"?',
    'options': ['Lagaan', 'Slumdog Millionaire', 'Life of Pi', '3 Idiots'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'What is the name of the coffee shop in the TV show "Friends"?',
    'options': ['Central Perk', 'The Grind', 'Java House', 'Common Grounds'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which superhero is known as the "Man of Steel"?',
    'options': ['Batman', 'Superman', 'Iron Man', 'Thor'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Who played the character of Jack Sparrow in "Pirates of the Caribbean"?',
    'options': [
      'Orlando Bloom',
      'Johnny Depp',
      'Geoffrey Rush',
      'Javier Bardem',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which music streaming service uses a green logo with a play-button-like circle?',
    'options': ['Apple Music', 'Spotify', 'YouTube Music', 'Tidal'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the boy wizard in J.K. Rowling\'s famous series?',
    'options': [
      'Ron Weasley',
      'Harry Potter',
      'Neville Longbottom',
      'Draco Malfoy',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which animated series features the family "The Simpsons" living in Springfield?',
    'options': ['Family Guy', 'The Simpsons', 'South Park', 'American Dad'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which actress played Hermione Granger in the Harry Potter films?',
    'options': ['Emma Watson', 'Emma Stone', 'Emma Roberts', 'Emily Blunt'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the highest-grossing film of all time (as of recent records, unadjusted)?',
    'options': [
      'Avengers: Endgame',
      'Avatar',
      'Titanic',
      'Star Wars: The Force Awakens',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Which musical instrument is Ravi Shankar famous for playing?',
    'options': ['Tabla', 'Sitar', 'Flute', 'Veena'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which country produces the most films per year, sometimes referred to as the world\'s largest film industry by output?',
    'options': [
      'USA (Hollywood)',
      'India (Bollywood + regional)',
      'China',
      'Japan',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Who is the author of "The Lord of the Rings" trilogy?',
    'options': [
      'C.S. Lewis',
      'J.R.R. Tolkien',
      'George R.R. Martin',
      'J.K. Rowling',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which award is considered the highest honor in the American film industry?',
    'options': ['Golden Globe', 'Academy Award (Oscar)', 'Emmy', 'BAFTA'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional African kingdom in Marvel\'s "Black Panther"?',
    'options': ['Zamunda', 'Wakanda', 'Sokovia', 'Genosha'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which video game franchise features a character named Mario?',
    'options': ['Sonic', 'Super Mario', 'Sega', 'Crash Bandicoot'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which band was famously formed by John Lennon and Paul McCartney?',
    'options': ['The Rolling Stones', 'The Beatles', 'Queen', 'Pink Floyd'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which Indian singer is known as the "Nightingale of India"?',
    'options': [
      'Asha Bhosle',
      'Lata Mangeshkar',
      'Kavita Krishnamurthy',
      'Alka Yagnik',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the evil wizard in the "Harry Potter" series?',
    'options': [
      'Severus Snape',
      'Lord Voldemort',
      'Draco Malfoy',
      'Sirius Black',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which streaming giant produced the film "RRR" that gained international acclaim?',
    'options': ['Netflix', 'Amazon Prime Video', 'Disney+', 'HBO Max'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Who is known for playing Iron Man / Tony Stark in the Marvel Cinematic Universe?',
    'options': [
      'Chris Evans',
      'Robert Downey Jr.',
      'Chris Hemsworth',
      'Mark Ruffalo',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
];
