import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

Future<void> bulkUploadQuestionsBatch4() async {
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  final collection = firestore.collection('questions');

  for (final q in _batch4Questions) {
    final docRef = collection.doc();
    batch.set(docRef, q);
  }

  try {
    await batch.commit();
    debugPrint('✅ Uploaded ${_batch4Questions.length} questions (Batch 4)');
  } catch (e) {
    debugPrint('❌ Bulk upload failed: $e');
  }
}

final List<Map<String, dynamic>> _batch4Questions = [
  // ================= GENERAL (30) =================
  {
    'category': 'General',
    'question': 'What is the term for a person who repairs shoes?',
    'options': ['Tailor', 'Cobbler', 'Blacksmith', 'Carpenter'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a type of bread that is flat and unleavened?',
    'options': ['Croissant', 'Pita', 'Baguette', 'Brioche'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the name for a young sheep?',
    'options': ['Kid', 'Lamb', 'Foal', 'Calf'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which of these musical instruments is a percussion instrument?',
    'options': ['Violin', 'Flute', 'Drum', 'Trumpet'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What do you call a person who flies an airplane?',
    'options': ['Captain', 'Pilot', 'Navigator', 'Steward'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which of these is the correct term for a fear of spiders?',
    'options': ['Ophidiophobia', 'Arachnophobia', 'Entomophobia', 'Musophobia'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'What is the traditional Indian garment worn by men, wrapped around the waist?',
    'options': ['Kurta', 'Dhoti', 'Sherwani', 'Pagri'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which of these animals is known to sleep the most hours per day?',
    'options': ['Lion', 'Koala', 'Elephant', 'Horse'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the term for the outer layer of a tree trunk?',
    'options': ['Bark', 'Sap', 'Root', 'Pulp'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a common household spice used to add heat to food?',
    'options': ['Cinnamon', 'Chili powder', 'Nutmeg', 'Vanilla'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the name for a triangle with all sides equal?',
    'options': ['Scalene', 'Isosceles', 'Equilateral', 'Right-angled'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which of these is the correct plural of "mouse" (the animal)?',
    'options': ['Mouses', 'Mice', 'Mouse', 'Meese'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the name for a doctor who treats teeth?',
    'options': ['Optometrist', 'Dentist', 'Dermatologist', 'Podiatrist'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which of these fruits grows on a vine?',
    'options': ['Apple', 'Grape', 'Banana', 'Mango'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'What is the term for a word formed by rearranging the letters of another word?',
    'options': ['Synonym', 'Anagram', 'Acronym', 'Homophone'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a traditional Indian musical instrument played with a bow?',
    'options': ['Sitar', 'Sarangi', 'Tabla', 'Harmonium'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What is the common name for the fruit of the oak tree?',
    'options': ['Chestnut', 'Acorn', 'Walnut', 'Hazelnut'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which of these is used to sweeten food and is made by bees?',
    'options': ['Maple syrup', 'Honey', 'Molasses', 'Agave syrup'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the term for a group of wolves?',
    'options': ['Herd', 'Pack', 'Flock', 'Colony'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a common Indian breakfast dish made from fermented rice and lentil batter?',
    'options': ['Paratha', 'Dosa', 'Poha', 'Upma'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'What is the term for the smallest unit of currency, often coins?',
    'options': ['Note', 'Denomination', 'Cent/paisa', 'Bond'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which of these animals is known to be the only bird that can fly backwards?',
    'options': ['Sparrow', 'Hummingbird', 'Eagle', 'Parrot'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What is the correct term for a period of ten years?',
    'options': ['Century', 'Decade', 'Millennium', 'Era'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a popular Indian street food made of spiced potato in a fried shell?',
    'options': ['Samosa', 'Vada Pav', 'Golgappa/Panipuri', 'Kachori'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'What is the term for a shape that has all sides and angles equal?',
    'options': [
      'Irregular polygon',
      'Regular polygon',
      'Concave polygon',
      'Convex only',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which of these is the correct term for the young of a butterfly before metamorphosis?',
    'options': ['Larva/Caterpillar', 'Nymph', 'Pupa only', 'Maggot'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'What is the traditional greeting gesture in India involving joined palms?',
    'options': ['Salaam', 'Namaste', 'Adaab', 'Pranam'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a unit used to measure the brightness of light?',
    'options': ['Watt', 'Lumen', 'Volt', 'Ohm'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question':
        'What is the common name for the process of preserving food using salt or sugar?',
    'options': ['Fermentation', 'Curing', 'Pasteurization', 'Distillation'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'Which of these is the correct term for a baby kangaroo?',
    'options': ['Cub', 'Joey', 'Kid', 'Pup'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= SCIENCE (30) =================
  {
    'category': 'Science',
    'question': 'What is the chemical symbol for silver?',
    'options': ['Si', 'Sv', 'Ag', 'Al'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which part of a plant absorbs water from the soil?',
    'options': ['Leaf', 'Stem', 'Root', 'Flower'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the term for the change of state from gas to liquid?',
    'options': ['Evaporation', 'Condensation', 'Sublimation', 'Melting'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which scientist developed the periodic table of elements?',
    'options': [
      'Antoine Lavoisier',
      'Dmitri Mendeleev',
      'John Dalton',
      'Marie Curie',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the force that opposes motion between two surfaces?',
    'options': ['Gravity', 'Friction', 'Tension', 'Magnetism'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which of these organs filters toxins from the blood?',
    'options': ['Heart', 'Liver', 'Lungs', 'Stomach'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the term for animals that lay eggs?',
    'options': ['Viviparous', 'Oviparous', 'Ovoviviparous', 'Asexual'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which planet takes the longest to orbit the sun?',
    'options': ['Saturn', 'Uranus', 'Neptune', 'Pluto (dwarf planet)'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What is the medical term for high blood pressure?',
    'options': ['Hypotension', 'Hypertension', 'Arrhythmia', 'Tachycardia'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which gas do plants release during photosynthesis?',
    'options': ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the study of the human mind and behavior?',
    'options': ['Sociology', 'Psychology', 'Anthropology', 'Philosophy'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which of these is the hardest part of the human body?',
    'options': ['Bone', 'Nail', 'Tooth enamel', 'Cartilage'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What is the unit of measurement for atmospheric pressure?',
    'options': ['Pascal', 'Newton', 'Joule', 'Watt'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which of these is a function of the human respiratory system?',
    'options': ['Digest food', 'Exchange gases', 'Pump blood', 'Filter waste'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for an organism that lives on or in another organism, causing it harm?',
    'options': ['Symbiont', 'Parasite', 'Predator', 'Decomposer'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'Which of these elements is essential for building strong bones?',
    'options': ['Iron', 'Calcium', 'Potassium', 'Sodium'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the layer of gases surrounding the Earth?',
    'options': ['Stratosphere', 'Atmosphere', 'Ionosphere', 'Biosphere'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which scientist is known for developing the polio vaccine?',
    'options': [
      'Alexander Fleming',
      'Jonas Salk',
      'Louis Pasteur',
      'Edward Jenner',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the process by which cells divide to form two identical cells?',
    'options': ['Meiosis', 'Mitosis', 'Fertilization', 'Fusion'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which of these is NOT a greenhouse gas?',
    'options': ['Carbon dioxide', 'Methane', 'Nitrogen', 'Water vapor'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What is the common term for the "backbone" of the human body?',
    'options': ['Spinal column', 'Sternum', 'Pelvis', 'Rib cage'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which of these animals is cold-blooded?',
    'options': ['Dog', 'Snake', 'Cat', 'Elephant'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the number of protons in an atom\'s nucleus?',
    'options': ['Mass number', 'Atomic number', 'Isotope number', 'Valence'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which of these is a type of simple machine?',
    'options': ['Engine', 'Lever', 'Motor', 'Generator'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the natural process by which species change over generations?',
    'options': ['Mutation', 'Evolution', 'Adaptation only', 'Selection only'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'Which gas is most abundant in the Earth\'s atmosphere by volume?',
    'options': ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the medical term for the inflammation of the appendix?',
    'options': ['Arthritis', 'Appendicitis', 'Bronchitis', 'Gastritis'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which of these is used to detect earthquakes?',
    'options': ['Barometer', 'Seismograph', 'Thermometer', 'Anemometer'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the term for a rock formed from cooled magma or lava?',
    'options': ['Sedimentary', 'Metamorphic', 'Igneous', 'Composite'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which of these is the human body\'s largest internal organ?',
    'options': ['Liver', 'Lungs', 'Brain', 'Kidney'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= HISTORY (30) =================
  {
    'category': 'History',
    'question': 'Who was the founder of the Delhi Sultanate?',
    'options': ['Qutb-ud-din Aibak', 'Muhammad Ghori', 'Iltutmish', 'Balban'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Which war ended with the Treaty of Sevres in 1920?',
    'options': [
      'World War I (Ottoman aftermath)',
      'World War II',
      'Crimean War',
      'Balkan Wars',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Who was the first Chief Justice of India?',
    'options': [
      'H.J. Kania',
      'M. Patanjali Sastri',
      'B.K. Mukherjea',
      'S.R. Das',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'The Non-Cooperation Movement was launched by Gandhi in which year?',
    'options': ['1917', '1920', '1930', '1942'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which ancient civilization built Machu Picchu?',
    'options': ['Aztec', 'Maya', 'Inca', 'Olmec'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the Roman emperor during the burning of Rome?',
    'options': ['Augustus', 'Nero', 'Caligula', 'Claudius'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The Simon Commission visited India in which year?',
    'options': ['1919', '1928', '1935', '1942'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which explorer was the first to circumnavigate the globe (expedition completed after his death)?',
    'options': [
      'Christopher Columbus',
      'Ferdinand Magellan',
      'Vasco da Gama',
      'James Cook',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the leader of the Zulu Kingdom known for military reforms?',
    'options': ['Shaka Zulu', 'Cetshwayo', 'Dingane', 'Mpande'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which Indian state was formed on linguistic basis first, in 1953?',
    'options': ['Maharashtra', 'Andhra Pradesh', 'Karnataka', 'Kerala'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'The Vietnam War primarily involved which two ideological sides?',
    'options': [
      'Democracy vs Monarchy',
      'Communism vs Capitalism (North vs South)',
      'Colonialism vs Independence only',
      'Religious factions',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the Egyptian pharaoh whose tomb was famously discovered nearly intact in 1922?',
    'options': ['Ramses II', 'Tutankhamun', 'Akhenaten', 'Thutmose III'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which Indian city was the capital of the Vijayanagara Empire?',
    'options': ['Mysore', 'Hampi', 'Madurai', 'Thanjavur'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Who led the Haitian Revolution against French colonial rule?',
    'options': [
      'Toussaint Louverture',
      'Simon Bolivar',
      'Jose de San Martin',
      'Miguel Hidalgo',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The Battle of Hastings in 1066 was fought in which country?',
    'options': ['France', 'England', 'Scotland', 'Ireland'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which Indian leader is credited with the phrase "Give me blood, and I shall give you freedom"?',
    'options': [
      'Bhagat Singh',
      'Subhash Chandra Bose',
      'Jawaharlal Nehru',
      'Lal Bahadur Shastri',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the first president of the United States to resign from office?',
    'options': [
      'Richard Nixon',
      'Andrew Johnson',
      'Ulysses Grant',
      'Warren Harding',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which empire was ruled by the "Habsburg" dynasty for centuries?',
    'options': [
      'Ottoman Empire',
      'Austro-Hungarian Empire',
      'Russian Empire',
      'British Empire',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'The Indian Rebellion of 1857 is also known by which other name?',
    'options': [
      'Sepoy Mutiny',
      'Salt March',
      'Quit India Movement',
      'Non-Cooperation Movement',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the first President of independent India?',
    'options': [
      'Jawaharlal Nehru',
      'Dr. Rajendra Prasad',
      'Sardar Patel',
      'C. Rajagopalachari',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Which ancient wonder was located in Babylon?',
    'options': [
      'Colossus of Rhodes',
      'Hanging Gardens',
      'Temple of Artemis',
      'Statue of Zeus',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the Chinese leader who led the Communist Revolution in 1949?',
    'options': ['Chiang Kai-shek', 'Mao Zedong', 'Deng Xiaoping', 'Zhou Enlai'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which Indian ruler is known for his naval fort at Sindhudurg?',
    'options': ['Shivaji Maharaj', 'Sambhaji', 'Bajirao I', 'Tipu Sultan'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'The Marshall Plan was implemented to help rebuild which region after World War II?',
    'options': ['Asia', 'Western Europe', 'Africa', 'South America'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Who was the ruler known as Tipu Sultan\'s father, also a ruler of Mysore?',
    'options': [
      'Haidar Ali',
      'Krishnaraja Wodeyar',
      'Chikka Devaraja',
      'Nanjaraja',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which country was divided into North and South after World War II, leading to a major war in the 1950s?',
    'options': ['Vietnam', 'Korea', 'Germany', 'China'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the Indian freedom fighter hanged for the Kakori conspiracy?',
    'options': [
      'Bhagat Singh',
      'Ram Prasad Bismil',
      'Chandrashekhar Azad',
      'Ashfaqulla Khan',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Which country did Napoleon Bonaparte become emperor of?',
    'options': ['Italy', 'France', 'Spain', 'Austria'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The ancient Silk Road primarily connected which two regions?',
    'options': [
      'Europe and Africa',
      'China and the Mediterranean/Europe',
      'India and Southeast Asia',
      'Americas and Europe',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Who was the last British Viceroy of India?',
    'options': [
      'Lord Wavell',
      'Lord Mountbatten',
      'Lord Linlithgow',
      'Lord Curzon',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= GEOGRAPHY (30) =================
  {
    'category': 'Geography',
    'question': 'What is the capital of New Zealand?',
    'options': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian state is known as the "Land of Five Rivers"?',
    'options': ['Haryana', 'Punjab', 'Rajasthan', 'Himachal Pradesh'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Cuba?',
    'options': ['Santiago', 'Havana', 'Varadero', 'Camaguey'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country is the largest exporter of oil in the world?',
    'options': ['USA', 'Russia', 'Saudi Arabia', 'Iraq'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Chile?',
    'options': ['Valparaiso', 'Santiago', 'Concepcion', 'Antofagasta'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which Indian city is known as the "Manchester of India" for its textile industry?',
    'options': ['Surat', 'Ahmedabad', 'Mumbai', 'Coimbatore'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Colombia?',
    'options': ['Medellin', 'Bogota', 'Cali', 'Cartagena'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which is the largest lake in India?',
    'options': ['Chilika Lake', 'Vembanad Lake', 'Wular Lake', 'Dal Lake'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Peru?',
    'options': ['Cusco', 'Lima', 'Arequipa', 'Trujillo'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country has the longest coastline in the world?',
    'options': ['Russia', 'Canada', 'Indonesia', 'Australia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Venezuela?',
    'options': ['Maracaibo', 'Caracas', 'Valencia', 'Barquisimeto'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian city is called the "City of Nawabs"?',
    'options': ['Bhopal', 'Lucknow', 'Hyderabad', 'Rampur'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Morocco?',
    'options': ['Casablanca', 'Rabat', 'Marrakesh', 'Fez'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which strait separates Sri Lanka from mainland India?',
    'options': ['Palk Strait', 'Bass Strait', 'Torres Strait', 'Bering Strait'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Iran?',
    'options': ['Isfahan', 'Tehran', 'Shiraz', 'Mashhad'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which Indian state is the only one with a coastline on both the Arabian Sea and shares no border with any other country?',
    'options': ['Goa', 'Kerala', 'Karnataka', 'Maharashtra'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Iraq?',
    'options': ['Basra', 'Baghdad', 'Mosul', 'Erbil'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which is the largest freshwater lake in the world by surface area?',
    'options': ['Lake Baikal', 'Lake Superior', 'Lake Victoria', 'Caspian Sea'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question':
        'What is the capital of Israel (as claimed and recognized by some countries)?',
    'options': ['Tel Aviv', 'Jerusalem', 'Haifa', 'Eilat'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which Indian river is known as the "Sorrow of Bihar" due to frequent flooding?',
    'options': ['Ganga', 'Kosi', 'Son', 'Gandak'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Qatar?',
    'options': ['Dubai', 'Doha', 'Abu Dhabi', 'Manama'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which mountain peak is the second highest in the world?',
    'options': ['Kangchenjunga', 'K2', 'Lhotse', 'Makalu'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of the United Arab Emirates?',
    'options': ['Dubai', 'Sharjah', 'Abu Dhabi', 'Ajman'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian state is often called the "Rice Bowl of India"?',
    'options': [
      'Punjab',
      'West Bengal',
      'Andhra Pradesh',
      'Both West Bengal and Andhra Pradesh',
    ],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Singapore?',
    'options': [
      'Singapore itself is a city-state',
      'Kuala Lumpur',
      'Jakarta',
      'Manila',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which continent has both the largest and smallest countries by area?',
    'options': ['Europe', 'Asia', 'Africa', 'South America'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Jordan?',
    'options': ['Petra', 'Amman', 'Aqaba', 'Zarqa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which Indian city is the southernmost tip of mainland India, a popular tourist point?',
    'options': ['Kanyakumari', 'Rameswaram', 'Kochi', 'Trivandrum'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Myanmar?',
    'options': ['Yangon', 'Naypyidaw', 'Mandalay', 'Bagan'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which of these is a landlocked country in Europe?',
    'options': ['Portugal', 'Switzerland', 'Italy', 'Greece'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= SPORTS (30) =================
  {
    'category': 'Sports',
    'question': 'Which Indian cricketer is known for the "Helicopter Shot"?',
    'options': ['Virat Kohli', 'MS Dhoni', 'Rohit Sharma', 'Suresh Raina'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a shot in cricket that clears the boundary without bouncing?',
    'options': ['Boundary', 'Six', 'Four', 'Maximum only in T20'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which country won the FIFA World Cup 2022?',
    'options': ['France', 'Brazil', 'Argentina', 'Croatia'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a football match ending with no goals scored by either team?',
    'options': ['Draw', 'Goalless draw/Nil-nil', 'Tie', 'Blank match'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian city hosts the annual Beighton Cup hockey tournament?',
    'options': ['Mumbai', 'Kolkata', 'Delhi', 'Chennai'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the maximum number of overs in a One Day International (ODI) cricket match per side?',
    'options': ['20', '40', '50', '60'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which tennis Grand Slam is played on hard courts in the USA?',
    'options': ['Wimbledon', 'French Open', 'US Open', 'Australian Open'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian boxer won an Olympic bronze medal in 2008 Beijing Olympics?',
    'options': ['Mary Kom', 'Vijender Singh', 'Vikas Krishan', 'Akhil Kumar'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for the area a goalkeeper can handle the ball within in football?',
    'options': [
      'Center circle',
      'Penalty area',
      'Technical area',
      'Corner arc',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which country has won the most medals in Olympic weightlifting historically among Asian nations?',
    'options': ['India', 'China', 'Japan', 'South Korea'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the standard weight category division system in boxing based on?',
    'options': ['Height', 'Age', 'Body weight', 'Reach'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian golfer became the first Indian to win a European Tour event?',
    'options': [
      'Jeev Milkha Singh',
      'Anirban Lahiri',
      'Shiv Kapur',
      'Arjun Atwal',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for the line that separates each player\'s court in tennis and badminton?',
    'options': ['Baseline', 'Net', 'Service line', 'Sideline'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which country is credited with the origin of the modern Olympic Games in 1896?',
    'options': ['Italy', 'Greece', 'France', 'England'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for scoring in archery when the arrow hits the exact center of the target?',
    'options': ['Bullseye', 'Perfect shot', 'Center hit', 'Gold hit'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian chess player became the youngest World Chess Champion in 2024?',
    'options': [
      'Viswanathan Anand',
      'Gukesh Dommaraju',
      'Praggnanandhaa',
      'Vidit Gujrathi',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a cricket delivery that spins away from a right-handed batsman after pitching (bowled by a leg-spinner)?',
    'options': ['Off break', 'Leg break', 'Googly', 'Doosra'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'Which country hosts the prestigious "Wimbledon" tennis championship every year?',
    'options': ['USA', 'France', 'England', 'Australia'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a player who specializes in both batting and bowling in cricket?',
    'options': [
      'Specialist',
      'All-rounder',
      'Wicketkeeper-batsman',
      'Pinch hitter',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian athlete won India\'s first individual Olympic gold medal (2008, shooting)?',
    'options': [
      'Rajyavardhan Singh Rathore',
      'Abhinav Bindra',
      'Gagan Narang',
      'Vijay Kumar',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a serve in tennis that the opponent fails to touch?',
    'options': ['Fault', 'Ace', 'Let', 'Winner'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which country is famous for producing many world champions in long-distance running, especially marathons?',
    'options': ['Jamaica', 'Kenya', 'USA', 'Russia'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'What is the term for the small ball used in golf?',
    'options': ['Golf ball', 'Puck', 'Birdie ball', 'Tee ball'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian sport uses a small disc called a "puck" moved by a striker on a board?',
    'options': ['Carrom', 'Table Tennis', 'Air Hockey', 'Snooker'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a batsman being out without facing a single ball in cricket?',
    'options': ['Golden duck', 'Diamond duck', 'Silver duck', 'Platinum duck'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which country won the most medals at the 2020 Tokyo Olympics?',
    'options': ['China', 'USA', 'Japan', 'Russia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for the trophy awarded to the winner of the English Premier League?',
    'options': [
      'FA Cup',
      'Premier League Trophy',
      'Community Shield',
      'League Cup',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian athlete is the first Indian woman to win an Olympic medal in wrestling?',
    'options': [
      'Geeta Phogat',
      'Sakshi Malik',
      'Vinesh Phogat',
      'Babita Phogat',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a shot in badminton hit steeply downward?',
    'options': ['Clear', 'Smash', 'Drop shot', 'Lob'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country invented the sport of Rugby?',
    'options': ['France', 'England', 'Wales', 'Scotland'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= ENTERTAINMENT (30) =================
  {
    'category': 'Entertainment',
    'question':
        'Which Indian film composer is known for the Slumdog Millionaire Oscar-winning score?',
    'options': [
      'Shankar Mahadevan',
      'A.R. Rahman',
      'Ilaiyaraaja',
      'Vishal Bhardwaj',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional detective agency in "Scooby-Doo"?',
    'options': [
      'Mystery Machine (van, not agency)',
      'Mystery Inc.',
      'Ghost Hunters',
      'Case Solvers',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which actor played the lead role of "Forrest Gump"?',
    'options': [
      'Tom Hanks',
      'Kevin Costner',
      'Robin Williams',
      'Dustin Hoffman',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian music reality show is known for discovering singing talent, hosted for many seasons?',
    'options': [
      'Indian Idol',
      'Sa Re Ga Ma Pa',
      'Both are singing shows',
      'The Voice India',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional bear who loves marmalade sandwiches?',
    'options': ['Winnie the Pooh', 'Paddington', 'Yogi Bear', 'Baloo'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which musician is known as the "Queen of Pop"?',
    'options': ['Whitney Houston', 'Madonna', 'Mariah Carey', 'Celine Dion'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian film is known for the record-breaking song "Naatu Naatu" that won an Oscar?',
    'options': ['Baahubali 2', 'RRR', 'KGF Chapter 2', 'Pushpa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional superhero team that includes Iron Man, Thor, and Captain America?',
    'options': ['Justice League', 'Avengers', 'X-Men', 'Fantastic Four'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actor is known for playing the role of "Munna Bhai" in the popular film series?',
    'options': ['Salman Khan', 'Sanjay Dutt', 'Ajay Devgn', 'Akshay Kumar'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional wizarding newspaper in Harry Potter?',
    'options': [
      'The Quibbler',
      'The Daily Prophet',
      'Witch Weekly',
      'Both Daily Prophet and Quibbler exist',
    ],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Which singer is known for the song "Rolling in the Deep"?',
    'options': ['Amy Winehouse', 'Adele', 'Sam Smith', 'Duffy'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actor won a National Award for the movie "Pan Singh Tomar"?',
    'options': [
      'Manoj Bajpayee',
      'Irrfan Khan',
      'Nawazuddin Siddiqui',
      'Pankaj Tripathi',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional talking lion in "The Chronicles of Narnia"?',
    'options': ['Simba', 'Aslan', 'Leo', 'Mufasa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian singer is famous for "Tum Hi Ho" from Aashiqui 2?',
    'options': ['Arijit Singh', 'Mohit Chauhan', 'KK', 'Atif Aslam'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional galaxy far, far away in "Star Wars"?',
    'options': [
      'It is unnamed, simply "a galaxy far, far away"',
      'The Milky Way',
      'Andromeda',
      'Alderaan Galaxy',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Bollywood movie franchise features the character "Don" played by both Amitabh Bachchan and Shah Rukh Khan?',
    'options': ['Don', 'Baazigar', 'Vijay', 'Deewar'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which classical music form is South Indian in origin, distinct from Hindustani music?',
    'options': ['Carnatic music', 'Sufi music', 'Ghazal', 'Qawwali'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional wizarding sport equipment shop in Diagon Alley?',
    'options': [
      'Quality Quidditch Supplies',
      'Flourish and Blotts',
      'Madam Malkins',
      'Ollivanders',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which actor is known for playing "Wolverine" in the X-Men film series?',
    'options': [
      'Ryan Reynolds',
      'Hugh Jackman',
      'Patrick Stewart',
      'Ian McKellen',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which Indian film director is known for "Gangs of Wasseypur"?',
    'options': [
      'Anurag Kashyap',
      'Dibakar Banerjee',
      'Vishal Bhardwaj',
      'Sudhir Mishra',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the puppet character famous for "Sesame Street" who lives in a trash can?',
    'options': ['Big Bird', 'Oscar the Grouch', 'Elmo', 'Cookie Monster'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian TV series is centered around a fictional courtroom drama and quiz-like general knowledge segments?',
    'options': [
      'Kaun Banega Crorepati',
      'CID',
      'Adaalat',
      'Both CID and Adaalat are crime/legal dramas',
    ],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which movie features the famous line "Houston, we have a problem"?',
    'options': ['Gravity', 'Apollo 13', 'The Martian', 'Interstellar'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actress is known as the "Dream Girl" of Bollywood from the classic era?',
    'options': ['Hema Malini', 'Rekha', 'Zeenat Aman', 'Sharmila Tagore'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional wizarding prison in Harry Potter?',
    'options': [
      'Nurmengard',
      'Azkaban',
      'Malfoy Manor dungeon',
      'The Ministry cells',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which musician is known as the lead guitarist and co-founder of the band Guns N\' Roses?',
    'options': [
      'Slash',
      'Axl Rose (vocalist, not guitarist)',
      'Jimmy Page',
      'Eddie Van Halen',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actor is known for his roles in "Sholay" as the villain "Gabbar Singh"?',
    'options': ['Amjad Khan', 'Pran', 'Amrish Puri', 'Prem Chopra'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional country club in the movie "Caddyshack"? (general trivia on golf movies)',
    'options': [
      'Bushwood Country Club',
      'Pebble Beach',
      'Augusta',
      'Pine Valley',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian playback singer is often called the "Melody King" of Bollywood?',
    'options': [
      'Kishore Kumar',
      'Mohammed Rafi',
      'Both are legendary singers',
      'Manna Dey',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which movie features a group of toys coming to life when humans are not around?',
    'options': [
      'Toy Story',
      'The Brave Little Toaster',
      'Small Soldiers',
      'Chucky',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
];
