// bulk_upload_questions_batch3.dart
//
// Same usage as Batch 1 & 2 — copy into your project, call
// `await bulkUploadQuestionsBatch3();` ONCE in main.dart (after Firebase.initializeApp()),
// run the app with a full stop+run (not hot reload), confirm the count increased,
// then REMOVE the call.
//
// This is BATCH 3 — another 180 questions, all different from Batch 1 & 2.
// Running all three batches gives you 540 total questions.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

Future<void> bulkUploadQuestionsBatch3() async {
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  final collection = firestore.collection('questions');

  for (final q in _batch3Questions) {
    final docRef = collection.doc();
    batch.set(docRef, q);
  }

  try {
    await batch.commit();
    debugPrint('✅ Uploaded ${_batch3Questions.length} questions (Batch 3)');
  } catch (e) {
    debugPrint('❌ Bulk upload failed: $e');
  }
}

final List<Map<String, dynamic>> _batch3Questions = [
  // ================= GENERAL (30) =================
  {
    'category': 'General',
    'question': 'What is the term for a shape with eight sides?',
    'options': ['Hexagon', 'Heptagon', 'Octagon', 'Nonagon'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which of these is a type of cloud found high in the sky?',
    'options': ['Cumulus', 'Cirrus', 'Stratus', 'Nimbus'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question':
        'What is the term for a word that means the same as another word?',
    'options': ['Antonym', 'Synonym', 'Homonym', 'Acronym'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which utensil is traditionally used to eat sushi?',
    'options': ['Fork', 'Spoon', 'Chopsticks', 'Skewer'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the term for baby cat?',
    'options': ['Cub', 'Kitten', 'Puppy', 'Calf'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which is the tallest animal in the world?',
    'options': ['Elephant', 'Giraffe', 'Ostrich', 'Camel'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What do you call a person who studies stars and space?',
    'options': ['Biologist', 'Astronomer', 'Geologist', 'Meteorologist'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which shape has no corners and no edges?',
    'options': ['Square', 'Triangle', 'Circle', 'Rectangle'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'What is the term for money given for good service at a restaurant?',
    'options': ['Tax', 'Tip', 'Bill', 'Fee'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which of these is the largest species of penguin?',
    'options': [
      'King Penguin',
      'Emperor Penguin',
      'Adelie Penguin',
      'Gentoo Penguin',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the traditional Japanese art of paper folding called?',
    'options': ['Ikebana', 'Origami', 'Bonsai', 'Sumi-e'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which fruit is known to float on water because it is mostly air inside?',
    'options': ['Apple', 'Orange', 'Watermelon', 'Grape'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the name for a shape with ten sides?',
    'options': ['Octagon', 'Nonagon', 'Decagon', 'Dodecagon'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'Which of these is NOT a type of pasta?',
    'options': ['Penne', 'Fusilli', 'Risotto', 'Farfalle'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the term for a person who cannot sleep easily?',
    'options': ['Narcoleptic', 'Insomniac', 'Somnambulist', 'Lethargic'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which planet is closest to the sun?',
    'options': ['Venus', 'Earth', 'Mercury', 'Mars'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What do you call the study of ancient fossils?',
    'options': ['Archaeology', 'Paleontology', 'Anthropology', 'Geology'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'Which of these numbers is a prime number?',
    'options': ['9', '15', '17', '21'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the common name for sodium chloride?',
    'options': ['Sugar', 'Salt', 'Baking soda', 'Vinegar'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which animal is known for changing its color to blend with surroundings?',
    'options': ['Iguana', 'Chameleon', 'Gecko', 'Salamander'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is a group of fish called?',
    'options': ['Herd', 'Flock', 'School', 'Pack'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which of these is the correct term for fear of heights?',
    'options': ['Claustrophobia', 'Acrophobia', 'Arachnophobia', 'Agoraphobia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What is the primary ingredient in guacamole?',
    'options': ['Tomato', 'Avocado', 'Onion', 'Lime'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which of these is a nocturnal bird known for its hooting sound?',
    'options': ['Eagle', 'Owl', 'Falcon', 'Hawk'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'What is the term for the imaginary line around the middle of the Earth?',
    'options': ['Meridian', 'Equator', 'Tropic', 'Axis'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which of these is used to measure wind speed?',
    'options': ['Barometer', 'Anemometer', 'Thermometer', 'Hygrometer'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question':
        'What is the traditional Indian sweet made from milk solids called?',
    'options': ['Jalebi', 'Khoya/Mawa sweets', 'Halwa', 'Ladoo'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which of these creatures is a marsupial known for carrying young in a pouch?',
    'options': ['Sloth', 'Kangaroo', 'Anteater', 'Armadillo'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the name for the natural satellite of Earth?',
    'options': ['Star', 'Moon', 'Comet', 'Asteroid'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which of these is the correct plural of "cactus"?',
    'options': [
      'Cactuses only',
      'Cacti',
      'Both cacti and cactuses are correct',
      'Cactus',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= SCIENCE (30) =================
  {
    'category': 'Science',
    'question': 'What is the chemical symbol for iron?',
    'options': ['Ir', 'In', 'Fe', 'I'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'Which scientist proposed the theory of evolution by natural selection?',
    'options': [
      'Gregor Mendel',
      'Charles Darwin',
      'Louis Pasteur',
      'Carl Linnaeus',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the study of fungi called?',
    'options': ['Mycology', 'Botany', 'Zoology', 'Virology'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which organ produces bile in the human body?',
    'options': ['Kidney', 'Liver', 'Pancreas', 'Stomach'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the average distance from the Earth to the Sun?',
    'options': ['Light year', 'Astronomical unit', 'Parsec', 'Kilometer'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which gas is used by welders and is the lightest element?',
    'options': ['Helium', 'Hydrogen', 'Nitrogen', 'Oxygen'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for plants that complete their life cycle in one year?',
    'options': ['Perennial', 'Biennial', 'Annual', 'Deciduous'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which part of the brain controls balance and coordination?',
    'options': ['Cerebrum', 'Cerebellum', 'Medulla', 'Hypothalamus'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What is the chemical name for rust?',
    'options': ['Iron oxide', 'Iron carbide', 'Iron sulfate', 'Iron nitrate'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which of these is a renewable source of energy?',
    'options': ['Coal', 'Natural gas', 'Solar power', 'Petroleum'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for an animal that eats both plants and meat?',
    'options': ['Herbivore', 'Carnivore', 'Omnivore', 'Detritivore'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which scientist is known for the famous equation E=mc²?',
    'options': [
      'Isaac Newton',
      'Albert Einstein',
      'Stephen Hawking',
      'Niels Bohr',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the outermost layer of human skin called?',
    'options': ['Dermis', 'Epidermis', 'Hypodermis', 'Subcutis'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which planet is famous for having the Great Red Spot storm?',
    'options': ['Mars', 'Jupiter', 'Saturn', 'Neptune'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the term for the study of insects?',
    'options': ['Entomology', 'Ornithology', 'Herpetology', 'Ichthyology'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which vitamin helps in blood clotting?',
    'options': ['Vitamin A', 'Vitamin C', 'Vitamin E', 'Vitamin K'],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What is the process of splitting an atom\'s nucleus called?',
    'options': ['Fusion', 'Fission', 'Ionization', 'Diffusion'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which of these is the largest planet in our solar system?',
    'options': ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the common name for the compound H2O2?',
    'options': ['Water', 'Hydrogen peroxide', 'Ammonia', 'Sulfuric acid'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which sense organ is responsible for hearing?',
    'options': ['Eye', 'Ear', 'Nose', 'Tongue'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for organisms that live in extreme environments like hot springs?',
    'options': [
      'Extremophiles',
      'Thermophiles only',
      'Halophiles only',
      'Mesophiles',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question':
        'Which blood vessel carries oxygenated blood away from the heart?',
    'options': ['Vein', 'Artery', 'Capillary', 'Venule'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the name of the force that pulls objects toward the center of the Earth?',
    'options': ['Magnetism', 'Gravity', 'Friction', 'Tension'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which gas is essential for combustion (burning)?',
    'options': ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Helium'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the term for a baby frog before it becomes an adult?',
    'options': ['Larva', 'Tadpole', 'Nymph', 'Pupa'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which of these elements is a noble gas?',
    'options': ['Chlorine', 'Neon', 'Sulfur', 'Bromine'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the main function of white blood cells?',
    'options': [
      'Carry oxygen',
      'Fight infection',
      'Clot blood',
      'Transport nutrients',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'Which scientist is credited with discovering gravity through a falling apple story?',
    'options': [
      'Albert Einstein',
      'Isaac Newton',
      'Galileo Galilei',
      'Johannes Kepler',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the term for the distance light travels in one year?',
    'options': ['Astronomical unit', 'Parsec', 'Light year', 'Kilometer'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which of these is NOT a state of matter?',
    'options': ['Solid', 'Liquid', 'Gas', 'Energy'],
    'correctAnswerIndex': 3,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= HISTORY (30) =================
  {
    'category': 'History',
    'question': 'Who was the first female Prime Minister in the world?',
    'options': [
      'Indira Gandhi',
      'Sirimavo Bandaranaike',
      'Golda Meir',
      'Margaret Thatcher',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which Indian dynasty is known for constructing the Ellora and Ajanta Caves?',
    'options': ['Maurya', 'Gupta', 'Chalukya and Rashtrakuta', 'Chola'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The Magna Carta was signed in which country?',
    'options': ['France', 'England', 'Germany', 'Spain'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the founder of the Sikh religion?',
    'options': [
      'Guru Nanak',
      'Guru Gobind Singh',
      'Guru Arjan Dev',
      'Guru Amar Das',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which war is the "Battle of Waterloo" associated with?',
    'options': [
      'Napoleonic Wars',
      'World War I',
      'Hundred Years War',
      'Crimean War',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The Great Depression began in which year?',
    'options': ['1919', '1929', '1939', '1949'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the emperor of the Vijayanagara Empire known for his patronage of arts and literature?',
    'options': ['Krishnadevaraya', 'Bukka Raya', 'Harihara', 'Deva Raya'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which country did Alexander the Great rule before his conquests?',
    'options': ['Greece', 'Macedon', 'Persia', 'Egypt'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The American Civil War was fought primarily over which issue?',
    'options': ['Taxation', 'Slavery', 'Territory expansion', 'Religion'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the first man in space?',
    'options': ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'John Glenn'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Which Indian king is credited with unifying most of the Indian subcontinent under the Mauryan Empire?',
    'options': ['Ashoka', 'Chandragupta Maurya', 'Bindusara', 'Samudragupta'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'The Renaissance artist Leonardo da Vinci painted which famous portrait?',
    'options': ['The Last Supper', 'Mona Lisa', 'The Scream', 'Starry Night'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question':
        'Which Indian city served as the capital of British India before Delhi?',
    'options': ['Mumbai', 'Kolkata', 'Chennai', 'Lucknow'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the Prime Minister of India during the 1971 war with Pakistan?',
    'options': [
      'Lal Bahadur Shastri',
      'Indira Gandhi',
      'Morarji Desai',
      'Jawaharlal Nehru',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'The ancient Greek philosopher Socrates was the teacher of which other famous philosopher?',
    'options': ['Aristotle', 'Plato', 'Pythagoras', 'Epicurus'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Which Indian revolutionary is known for the phrase "Inquilab Zindabad"?',
    'options': ['Chandrashekhar Azad', 'Bhagat Singh', 'Rajguru', 'Sukhdev'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The Boston Tea Party took place in which country?',
    'options': ['England', 'USA', 'Canada', 'Ireland'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which Indian empire is known for the Sanchi Stupa?',
    'options': ['Maurya', 'Gupta', 'Chola', 'Kushan'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Who was the last Tsar of Russia before the revolution?',
    'options': [
      'Alexander III',
      'Nicholas II',
      'Peter the Great',
      'Ivan the Terrible',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The Mughal Empire was founded by which ruler?',
    'options': ['Akbar', 'Babur', 'Humayun', 'Shah Jahan'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Which country did Adolf Hitler invade in 1939, triggering World War II?',
    'options': ['France', 'Poland', 'Belgium', 'Austria'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the first Indian to win a Nobel Prize?',
    'options': [
      'C.V. Raman',
      'Rabindranath Tagore',
      'Mother Teresa',
      'Amartya Sen',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The ancient city of Pompeii was destroyed by which volcano?',
    'options': ['Mount Etna', 'Mount Vesuvius', 'Mount Fuji', 'Krakatoa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Which Indian queen fought against the British in the 1857 revolt?',
    'options': [
      'Rani Padmini',
      'Rani Lakshmibai',
      'Razia Sultana',
      'Ahilyabai Holkar',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the founder of the Maratha Empire?',
    'options': ['Bajirao I', 'Shivaji Maharaj', 'Sambhaji', 'Shahu Maharaj'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'The Suez Canal connects which two seas?',
    'options': [
      'Mediterranean and Red Sea',
      'Red Sea and Arabian Sea',
      'Mediterranean and Black Sea',
      'Atlantic and Pacific',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which Indian city is known as the birthplace of the Buddhist religion movement (where Buddha attained enlightenment)?',
    'options': ['Varanasi', 'Bodh Gaya', 'Sarnath', 'Kushinagar'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'The atomic bombs in 1945 were dropped on which two Japanese cities?',
    'options': [
      'Tokyo and Osaka',
      'Hiroshima and Nagasaki',
      'Kyoto and Kobe',
      'Yokohama and Nagoya',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who wrote the Indian Constitution as its chief architect?',
    'options': [
      'Jawaharlal Nehru',
      'B.R. Ambedkar',
      'Sardar Patel',
      'Rajendra Prasad',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question':
        'Which ancient wonder of the world was located in Alexandria, Egypt?',
    'options': [
      'Hanging Gardens',
      'Lighthouse of Alexandria',
      'Colossus of Rhodes',
      'Great Pyramid',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= GEOGRAPHY (30) =================
  {
    'category': 'Geography',
    'question': 'Which country is the largest by population in Africa?',
    'options': ['Egypt', 'Nigeria', 'Ethiopia', 'South Africa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Sri Lanka (administrative capital)?',
    'options': ['Colombo', 'Sri Jayawardenepura Kotte', 'Kandy', 'Galle'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which river is the longest in Africa?',
    'options': ['Congo', 'Niger', 'Nile', 'Zambezi'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Switzerland?',
    'options': ['Zurich', 'Geneva', 'Bern', 'Basel'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which is the smallest state in India by area?',
    'options': ['Sikkim', 'Goa', 'Tripura', 'Nagaland'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Nepal?',
    'options': ['Pokhara', 'Kathmandu', 'Lalitpur', 'Bhaktapur'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question':
        'Which country has the most official languages recognized by its constitution?',
    'options': ['India', 'South Africa', 'Switzerland', 'Bolivia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Bangladesh?',
    'options': ['Chittagong', 'Dhaka', 'Khulna', 'Sylhet'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which desert covers much of Rajasthan in India?',
    'options': ['Sahara', 'Thar', 'Gobi', 'Kalahari'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Malaysia?',
    'options': ['Penang', 'Kuala Lumpur', 'Johor Bahru', 'Malacca'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which mountain range runs along the western coast of India?',
    'options': ['Aravalli', 'Vindhya', 'Western Ghats', 'Satpura'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Austria?',
    'options': ['Salzburg', 'Vienna', 'Graz', 'Innsbruck'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian river is considered the holiest in Hinduism?',
    'options': ['Yamuna', 'Ganges', 'Saraswati', 'Godavari'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Poland?',
    'options': ['Krakow', 'Warsaw', 'Gdansk', 'Wroclaw'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which continent is the Amazon Rainforest primarily located in?',
    'options': ['Africa', 'South America', 'Asia', 'Australia'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Sweden?',
    'options': ['Gothenburg', 'Stockholm', 'Malmo', 'Uppsala'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which Indian city is located at the confluence of three rivers, Ganga, Yamuna, and mythical Saraswati?',
    'options': ['Varanasi', 'Prayagraj (Allahabad)', 'Haridwar', 'Rishikesh'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Pakistan?',
    'options': ['Karachi', 'Lahore', 'Islamabad', 'Peshawar'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which country is entirely surrounded by South Africa?',
    'options': ['Swaziland', 'Lesotho', 'Botswana', 'Namibia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Norway?',
    'options': ['Bergen', 'Oslo', 'Trondheim', 'Stavanger'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian hill station is known as the "Queen of Hills"?',
    'options': ['Shimla', 'Darjeeling', 'Mussoorie', 'Ooty'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Denmark?',
    'options': ['Aarhus', 'Copenhagen', 'Odense', 'Aalborg'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which African country is known for Victoria Falls, shared with Zimbabwe?',
    'options': ['Zambia', 'Botswana', 'Namibia', 'Malawi'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Belgium?',
    'options': ['Antwerp', 'Brussels', 'Ghent', 'Bruges'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian state is the largest producer of tea?',
    'options': ['Kerala', 'Assam', 'Tamil Nadu', 'West Bengal'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Ireland?',
    'options': ['Belfast', 'Dublin', 'Cork', 'Galway'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which is the coldest continent on Earth?',
    'options': ['Europe', 'Asia', 'Antarctica', 'North America'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Kenya?',
    'options': ['Mombasa', 'Nairobi', 'Kisumu', 'Nakuru'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian city is famously called the "Pink City"?',
    'options': ['Udaipur', 'Jaipur', 'Jodhpur', 'Jaisalmer'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of the Philippines?',
    'options': ['Cebu', 'Manila', 'Davao', 'Quezon City'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= SPORTS (30) =================
  {
    'category': 'Sports',
    'question': 'Which sport is played at the "Australian Open"?',
    'options': ['Golf', 'Tennis', 'Cricket', 'Swimming'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'How many events make up a decathlon?',
    'options': ['5', '7', '10', '12'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian badminton player won an Olympic silver medal in 2016?',
    'options': ['Saina Nehwal', 'P.V. Sindhu', 'Sania Mirza', 'Jwala Gutta'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'What is the term for a score of two under par in golf?',
    'options': ['Birdie', 'Eagle', 'Bogey', 'Albatross'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country won the first Cricket T20 World Cup in 2007?',
    'options': ['Pakistan', 'India', 'Australia', 'South Africa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are there in a doubles badminton match in total?',
    'options': ['2', '3', '4', '6'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian wrestler won a gold medal at the Commonwealth Games and is known for freestyle wrestling?',
    'options': [
      'Sushil Kumar',
      'Yogeshwar Dutt',
      'Bajrang Punia',
      'All of the above have won medals',
    ],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for the area in front of the goal in football where fouls result in penalty kicks?',
    'options': ['Center circle', 'Penalty box', 'Goal area', 'Halfway line'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country has won the most Rugby World Cups?',
    'options': ['New Zealand', 'South Africa', 'Australia', 'England'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are on an American football team on the field per side?',
    'options': ['9', '11', '13', '7'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian shooter won a gold medal at the 2021 Tokyo Olympics (Javelin)?',
    'options': [
      'Abhinav Bindra',
      'Neeraj Chopra',
      'Vijay Kumar',
      'Gagan Narang',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'What is the term for a tie score in tennis at 40-40?',
    'options': ['Advantage', 'Deuce', 'Match point', 'Tiebreak'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country is the birthplace of the martial art karate?',
    'options': ['China', 'Japan', 'South Korea', 'Thailand'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'How many minutes long is a standard football (soccer) match, excluding stoppage time?',
    'options': ['60', '80', '90', '120'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian city hosted the first Cricket World Cup match India ever won?',
    'options': ['Mumbai', 'Kolkata', 'Delhi', 'Chennai'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for winning all four Grand Slam tennis tournaments in a single calendar year?',
    'options': ['Grand Slam', 'Career Slam', 'Golden Slam', 'Triple Crown'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which sport is associated with the Ryder Cup?',
    'options': ['Tennis', 'Golf', 'Cricket', 'Rugby'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are on an ice hockey team on the ice per side (excluding goalie)?',
    'options': ['4', '5', '6', '7'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which Indian athlete is known as the "Flying Sikh"?',
    'options': ['P.T. Usha', 'Milkha Singh', 'Kapil Dev', 'Anju Bobby George'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a set of three strikes in a row in bowling?',
    'options': ['Triple', 'Turkey', 'Hat-trick', 'Perfect game'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which country invented the sport of golf?',
    'options': ['England', 'Scotland', 'Ireland', 'Wales'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'How many events are there in a heptathlon?',
    'options': ['5', '7', '9', '10'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian cricketer is the highest run-scorer in Test cricket history?',
    'options': [
      'Virat Kohli',
      'Sachin Tendulkar',
      'Rahul Dravid',
      'Sunil Gavaskar',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for the starting position in a swimming race?',
    'options': ['Blocks', 'Starting dive', 'Launch pad', 'Take-off'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which country co-hosted the 2019 Cricket World Cup as the sole host?',
    'options': ['India', 'England and Wales', 'Australia', 'South Africa'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'What is the term for a shot in basketball worth three points?',
    'options': ['Free throw', 'Layup', 'Three-pointer', 'Slam dunk'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian sport involves seven players trying to tag opponents while holding their breath and chanting?',
    'options': ['Gilli-danda', 'Kabaddi', 'Kho-Kho', 'Malkhamb'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'What is the maximum number of clubs a golfer can carry in a round?',
    'options': ['10', '12', '14', '16'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which country won the first Rugby World Cup in 1987?',
    'options': ['Australia', 'New Zealand', 'South Africa', 'England'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for the official who oversees a cricket match on the field?',
    'options': ['Referee', 'Umpire', 'Judge', 'Marshal'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },

  // ================= ENTERTAINMENT (30) =================
  {
    'category': 'Entertainment',
    'question':
        'Which Marvel superhero is also known as the "Merc with a Mouth"?',
    'options': ['Spider-Man', 'Deadpool', 'Wolverine', 'Iron Man'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Who wrote the play "Romeo and Juliet"?',
    'options': [
      'Charles Dickens',
      'William Shakespeare',
      'Jane Austen',
      'Mark Twain',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian film became the first to gross over 1000 crore rupees worldwide?',
    'options': ['Dangal', 'Baahubali 2', '3 Idiots', 'PK'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional detective created by Arthur Conan Doyle?',
    'options': [
      'Hercule Poirot',
      'Sherlock Holmes',
      'Sam Spade',
      'Philip Marlowe',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which pop star is known for the song "Shape of You"?',
    'options': ['Justin Bieber', 'Ed Sheeran', 'Shawn Mendes', 'Bruno Mars'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which animated film features a young lion prince named Simba?',
    'options': ['Madagascar', 'The Lion King', 'Kung Fu Panda', 'Zootopia'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Who played the character "Iron Man" opposite in Marvel films as "Captain America"?',
    'options': [
      'Chris Hemsworth',
      'Chris Evans',
      'Chris Pratt',
      'Mark Ruffalo',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which Indian classical dance form originated in Tamil Nadu?',
    'options': ['Kathak', 'Bharatanatyam', 'Odissi', 'Kuchipudi'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional ocean liner in the movie "Titanic"?',
    'options': ['Titanic', 'Britannic', 'Olympic', 'Lusitania'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which streaming platform released the show "Money Heist" (La Casa de Papel)?',
    'options': ['Amazon Prime', 'Netflix', 'Hulu', 'HBO'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Who is the author of the "A Song of Ice and Fire" series that inspired Game of Thrones?',
    'options': [
      'J.R.R. Tolkien',
      'George R.R. Martin',
      'Terry Pratchett',
      'Brandon Sanderson',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actress is known as the first Indian to win the Miss World title?',
    'options': [
      'Priyanka Chopra',
      'Aishwarya Rai',
      'Reita Faria',
      'Sushmita Sen',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'What is the name of the villain in Disney\'s "The Lion King"?',
    'options': ['Jafar', 'Scar', 'Gaston', 'Ursula'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which musician is known as "The Boss"?',
    'options': ['Bruce Springsteen', 'Bon Jovi', 'Billy Joel', 'Rod Stewart'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian film director is known for "Lagaan" and "Swades"?',
    'options': [
      'Karan Johar',
      'Ashutosh Gowariker',
      'Rajkumar Hirani',
      'Sanjay Leela Bhansali',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional wand-maker shop in Harry Potter?',
    'options': [
      'Flourish and Blotts',
      'Ollivanders',
      'Gringotts',
      'Weasleys\' Wizard Wheezes',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which video streaming platform is owned by Google?',
    'options': ['Netflix', 'YouTube', 'Vimeo', 'Twitch'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian singer is known for the song "Kesariya" from the movie Brahmastra?',
    'options': [
      'Arijit Singh',
      'Pritam (composer)',
      'Both are correct (Arijit sang, Pritam composed)',
      'Shreya Ghoshal',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional school of wizardry\'s rival Quidditch cup trophy?',
    'options': ['House Cup', 'Quidditch Cup', 'Triwizard Cup', 'Golden Snitch'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which actor is known for playing "The Joker" and winning an Oscar for it in 2019?',
    'options': [
      'Heath Ledger',
      'Joaquin Phoenix',
      'Jared Leto',
      'Jack Nicholson',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian TV show is known for the longest-running soap opera format?',
    'options': [
      'Kyunki Saas Bhi Kabhi Bahu Thi',
      'Taarak Mehta Ka Ooltah Chashmah',
      'CID',
      'Balika Vadhu',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional planet in the "Avatar" movie?',
    'options': ['Arrakis', 'Pandora', 'Krypton', 'Vulcan'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian composer is known for scoring music for "Baahubali" and "RRR"?',
    'options': [
      'A.R. Rahman',
      'M.M. Keeravani',
      'Ilaiyaraaja',
      'Anirudh Ravichander',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional wizard mentor in "The Lord of the Rings"?',
    'options': ['Dumbledore', 'Gandalf', 'Merlin', 'Saruman'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actor is known as the "Andhra Boy" and star of Baahubali?',
    'options': ['Ram Charan', 'Prabhas', 'Allu Arjun', 'Mahesh Babu'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which musical genre originated in Jamaica and is associated with Bob Marley?',
    'options': ['Reggae', 'Ska', 'Calypso', 'Soca'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'What is the name of the fictional bear in "The Jungle Book"?',
    'options': ['Baloo', 'Yogi', 'Winnie', 'Paddington'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian actress is known as the "First Lady of Indian Cinema" from the classic era?',
    'options': ['Nargis', 'Devika Rani', 'Madhubala', 'Meena Kumari'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which movie franchise features the phrase "With great power comes great responsibility"?',
    'options': ['Batman', 'Spider-Man', 'Superman', 'X-Men'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian music director duo is famously known as "Shankar-Ehsaan-Loy"?',
    'options': [
      'A trio, not a duo',
      'A duo of two composers',
      'A single composer using a stage name',
      'A rock band',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
];
