import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

Future<void> bulkUploadQuestionsBatch2() async {
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  final collection = firestore.collection('questions');

  for (final q in _batch2Questions) {
    final docRef = collection.doc();
    batch.set(docRef, q);
  }

  try {
    await batch.commit();
    debugPrint('✅ Uploaded ${_batch2Questions.length} questions (Batch 2)');
  } catch (e) {
    debugPrint('❌ Bulk upload failed: $e');
  }
}

Future<void> checkQuestionCount() async {
  final snapshot = await FirebaseFirestore.instance
      .collection('questions')
      .count()
      .get();
  debugPrint('📊 Total questions in Firestore: ${snapshot.count}');
}

final List<Map<String, dynamic>> _batch2Questions = [
  // ================= GENERAL (30) =================
  {
    'category': 'General',
    'question': 'What is the largest mammal in the world?',
    'options': ['African Elephant', 'Blue Whale', 'Giraffe', 'Polar Bear'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many players make up a standard chess set on one side?',
    'options': ['12', '14', '16', '18'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which shape has three sides?',
    'options': ['Square', 'Triangle', 'Pentagon', 'Hexagon'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the main ingredient of traditional bread?',
    'options': ['Rice flour', 'Wheat flour', 'Corn flour', 'Oat flour'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which of these is NOT a primary color?',
    'options': ['Red', 'Green', 'Blue', 'Yellow'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the currency used in the United Kingdom?',
    'options': ['Euro', 'Dollar', 'Pound Sterling', 'Franc'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many sides does a hexagon have?',
    'options': ['5', '6', '7', '8'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which festival is known as the "Festival of Lights" in India?',
    'options': ['Holi', 'Diwali', 'Navratri', 'Baisakhi'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What do bees produce?',
    'options': ['Silk', 'Honey', 'Wax only', 'Milk'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which is the fastest land animal?',
    'options': ['Lion', 'Cheetah', 'Horse', 'Leopard'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the standard number of squares on a chessboard?',
    'options': ['32', '48', '64', '81'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which gas is commonly used in party balloons to make them float?',
    'options': ['Oxygen', 'Helium', 'Hydrogen', 'Nitrogen'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the term for a baby dog?',
    'options': ['Cub', 'Kitten', 'Puppy', 'Foal'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which is the longest bone in the human body?',
    'options': ['Tibia', 'Femur', 'Humerus', 'Fibula'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'What is the capital city of the USA?',
    'options': ['New York', 'Washington D.C.', 'Los Angeles', 'Chicago'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'Which instrument is used to measure temperature?',
    'options': ['Barometer', 'Thermometer', 'Hygrometer', 'Altimeter'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the term for a group of lions called?',
    'options': ['Pack', 'Herd', 'Pride', 'Flock'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which precious stone is famously associated with the month of April?',
    'options': ['Ruby', 'Diamond', 'Emerald', 'Sapphire'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'What is the most widely practiced religion in the world by number of followers?',
    'options': ['Islam', 'Christianity', 'Hinduism', 'Buddhism'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which everyday object was invented by Alexander Graham Bell?',
    'options': ['Light bulb', 'Telephone', 'Radio', 'Television'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'How many minutes are there in a full day?',
    'options': ['1200', '1440', '1600', '1800'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which shape has four equal sides and four right angles?',
    'options': ['Rectangle', 'Square', 'Rhombus', 'Trapezoid'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'What do you call a word that is spelled the same forwards and backwards?',
    'options': ['Synonym', 'Palindrome', 'Acronym', 'Homophone'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'Which everyday drink is made from fermented grapes?',
    'options': ['Beer', 'Whiskey', 'Wine', 'Cider'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question': 'What is the largest species of big cat?',
    'options': ['Lion', 'Tiger', 'Jaguar', 'Leopard'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question': 'How many zeros are there in one million?',
    'options': ['4', '5', '6', '7'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'General',
    'question':
        'Which is the most populous city in the world (city proper, recent estimates)?',
    'options': ['Tokyo', 'Shanghai', 'Delhi', 'Mumbai'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What do you call a shape with five sides?',
    'options': ['Hexagon', 'Pentagon', 'Octagon', 'Heptagon'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'General',
    'question':
        'Which spice is derived from the Crocus flower and is the most expensive by weight?',
    'options': ['Cinnamon', 'Saffron', 'Turmeric', 'Cardamom'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'General',
    'question': 'What is the term for the study of maps?',
    'options': ['Geology', 'Cartography', 'Geography', 'Topology'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= SCIENCE (30) =================
  {
    'category': 'Science',
    'question': 'What is the chemical symbol for gold?',
    'options': ['Go', 'Gd', 'Au', 'Ag'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the study of weather and climate called?',
    'options': ['Geology', 'Meteorology', 'Astronomy', 'Ecology'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'Which part of the human eye controls the amount of light entering it?',
    'options': ['Retina', 'Cornea', 'Iris', 'Lens'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the chemical formula for glucose?',
    'options': ['C6H12O6', 'C2H6O', 'CH4', 'C6H6'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'How many bones are there in the human skull?',
    'options': ['18', '22', '26', '30'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What is the primary function of red blood cells?',
    'options': [
      'Fight infection',
      'Carry oxygen',
      'Clot blood',
      'Produce hormones',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which planet has the most prominent ring system?',
    'options': ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'What is the term for animals without a backbone?',
    'options': ['Vertebrates', 'Invertebrates', 'Mammals', 'Amphibians'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which scientist is credited with discovering penicillin?',
    'options': [
      'Louis Pasteur',
      'Alexander Fleming',
      'Robert Koch',
      'Edward Jenner',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the unit used to measure the loudness of sound?',
    'options': ['Hertz', 'Decibel', 'Watt', 'Pascal'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which layer of the Earth is the hottest?',
    'options': ['Crust', 'Mantle', 'Outer core', 'Inner core'],
    'correctAnswerIndex': 3,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question':
        'What is the process called when a caterpillar transforms into a butterfly?',
    'options': ['Germination', 'Metamorphosis', 'Pollination', 'Fertilization'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'Which gas do humans exhale that plants use for photosynthesis?',
    'options': ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for a substance that speeds up a chemical reaction without being consumed?',
    'options': ['Reactant', 'Catalyst', 'Solvent', 'Enzyme inhibitor'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which organ in the human body produces insulin?',
    'options': ['Liver', 'Kidney', 'Pancreas', 'Spleen'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the closest star to Earth?',
    'options': ['Proxima Centauri', 'The Sun', 'Sirius', 'Alpha Centauri'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which type of energy is stored in a stretched rubber band?',
    'options': [
      'Kinetic energy',
      'Potential energy',
      'Thermal energy',
      'Chemical energy',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the main component of the sun\'s energy production process?',
    'options': [
      'Nuclear fission',
      'Nuclear fusion',
      'Combustion',
      'Radiation decay',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which vitamin deficiency causes scurvy?',
    'options': ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for water vapor turning directly into ice without becoming liquid?',
    'options': ['Condensation', 'Sublimation', 'Deposition', 'Evaporation'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question':
        'Which animal is known to have the largest brain relative to body size among mammals?',
    'options': ['Elephant', 'Dolphin', 'Human', 'Chimpanzee'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'What does DNA stand for?',
    'options': [
      'Deoxyribonucleic Acid',
      'Dinitrogen Acid',
      'Deoxyribose Nucleic Acid',
      'Dual Nucleic Acid',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'Which is the only mammal capable of true flight?',
    'options': ['Flying squirrel', 'Bat', 'Flying fox', 'Sugar glider'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the normal human body temperature in Celsius?',
    'options': ['35°C', '36.1°C', '37°C', '38.5°C'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question': 'Which particle in an atom has a negative charge?',
    'options': ['Proton', 'Neutron', 'Electron', 'Nucleus'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for the point in space where a black hole\'s gravity becomes inescapable?',
    'options': [
      'Event horizon',
      'Singularity',
      'Photon sphere',
      'Accretion disk',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Science',
    'question': 'Which of these animals is a marsupial?',
    'options': ['Koala', 'Panda', 'Otter', 'Raccoon'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question': 'What is the main function of the human kidneys?',
    'options': [
      'Pump blood',
      'Filter waste from blood',
      'Digest food',
      'Produce hormones only',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Science',
    'question':
        'Which gas is most responsible for the greenhouse effect on Earth?',
    'options': ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Science',
    'question':
        'What is the term for organisms that can produce their own food using sunlight?',
    'options': ['Heterotrophs', 'Autotrophs', 'Decomposers', 'Consumers'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= HISTORY (30) =================
  {
    'category': 'History',
    'question':
        'Who was the British Prime Minister during most of World War II?',
    'options': [
      'Neville Chamberlain',
      'Winston Churchill',
      'Clement Attlee',
      'Anthony Eden',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The Jallianwala Bagh massacre took place in which city?',
    'options': ['Delhi', 'Amritsar', 'Lahore', 'Lucknow'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which civilization is credited with inventing the wheel?',
    'options': ['Egyptian', 'Mesopotamian', 'Greek', 'Roman'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Who was the queen of Egypt famously associated with Julius Caesar and Mark Antony?',
    'options': ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Ankhesenamun'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'In which year did the Berlin Wall fall?',
    'options': ['1987', '1989', '1991', '1993'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the first man to step on the Moon?',
    'options': [
      'Buzz Aldrin',
      'Neil Armstrong',
      'Yuri Gagarin',
      'Michael Collins',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question':
        'The Indus Valley Civilization was located primarily in present-day which countries?',
    'options': [
      'India and Pakistan',
      'India and Bangladesh',
      'Pakistan and Afghanistan',
      'India and Nepal',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the leader of the Soviet Union during the Cuban Missile Crisis?',
    'options': [
      'Joseph Stalin',
      'Nikita Khrushchev',
      'Leonid Brezhnev',
      'Vladimir Lenin',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which Indian ruler is known for the Edicts inscribed on pillars promoting Buddhism?',
    'options': ['Chandragupta Maurya', 'Ashoka', 'Bimbisara', 'Harsha'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'The Cold War was primarily fought between which two nations/blocs?',
    'options': [
      'USA and China',
      'USA and USSR',
      'UK and Germany',
      'France and Russia',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Who wrote the "Communist Manifesto"?',
    'options': [
      'Vladimir Lenin',
      'Karl Marx and Friedrich Engels',
      'Joseph Stalin',
      'Mao Zedong',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The partition of India and Pakistan happened in which year?',
    'options': ['1945', '1946', '1947', '1948'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question':
        'Which explorer is credited with "discovering" America in 1492?',
    'options': [
      'Vasco da Gama',
      'Christopher Columbus',
      'Ferdinand Magellan',
      'James Cook',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Who was the first emperor of a unified China?',
    'options': ['Qin Shi Huang', 'Kublai Khan', 'Sun Yat-sen', 'Han Wudi'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Which country was the first to grant women the right to vote?',
    'options': ['USA', 'United Kingdom', 'New Zealand', 'France'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'The Battle of Panipat was fought multiple times in which country?',
    'options': ['Pakistan', 'India', 'Afghanistan', 'Bangladesh'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the leader of Nazi Germany during World War II?',
    'options': [
      'Joseph Goebbels',
      'Adolf Hitler',
      'Heinrich Himmler',
      'Hermann Göring',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Which year did the Russian Revolution take place?',
    'options': ['1905', '1917', '1922', '1929'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'Who was the first female Prime Minister of the United Kingdom?',
    'options': [
      'Theresa May',
      'Margaret Thatcher',
      'Liz Truss',
      'Queen Elizabeth II',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The ancient city of Rome was built on how many hills?',
    'options': ['5', '6', '7', '8'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'Which treaty officially ended World War I?',
    'options': [
      'Treaty of Paris',
      'Treaty of Versailles',
      'Treaty of Vienna',
      'Treaty of Rome',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Who was the Mughal emperor who built the Red Fort in Delhi?',
    'options': ['Akbar', 'Humayun', 'Shah Jahan', 'Jahangir'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The ancient Olympic Games originated in which country?',
    'options': ['Italy', 'Greece', 'Egypt', 'Turkey'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question': 'Who was the first Governor-General of independent India?',
    'options': [
      'Jawaharlal Nehru',
      'Lord Mountbatten',
      'C. Rajagopalachari',
      'Rajendra Prasad',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question':
        'Which empire was ruled from Constantinople for over a thousand years?',
    'options': [
      'Ottoman Empire',
      'Byzantine Empire',
      'Roman Empire',
      'Persian Empire',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'History',
    'question': 'The Wright Brothers are credited with inventing what?',
    'options': [
      'The automobile',
      'The airplane',
      'The telephone',
      'The steam engine',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'History',
    'question':
        'Which Indian leader gave the famous "Tryst with Destiny" speech?',
    'options': [
      'Mahatma Gandhi',
      'Jawaharlal Nehru',
      'Sardar Patel',
      'Subhash Chandra Bose',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question':
        'The ancient Library of Alexandria was located in which country?',
    'options': ['Greece', 'Egypt', 'Turkey', 'Italy'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'Which US President is on the 1 bill?',
    'options': [
      'Abraham Lincoln',
      'George Washington',
      'Thomas Jefferson',
      'Benjamin Franklin',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'History',
    'question': 'The Chola dynasty was primarily based in which part of India?',
    'options': ['North India', 'South India', 'East India', 'West India'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= GEOGRAPHY (30) =================
  {
    'category': 'Geography',
    'question': 'What is the capital of Russia?',
    'options': ['St. Petersburg', 'Moscow', 'Novosibirsk', 'Kazan'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which country is home to the Great Barrier Reef?',
    'options': ['Indonesia', 'Australia', 'Philippines', 'Fiji'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of China?',
    'options': ['Shanghai', 'Beijing', 'Hong Kong', 'Guangzhou'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian state has the longest coastline?',
    'options': ['Tamil Nadu', 'Gujarat', 'Andhra Pradesh', 'Maharashtra'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Mexico?',
    'options': ['Guadalajara', 'Mexico City', 'Cancun', 'Monterrey'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which continent has the most countries?',
    'options': ['Asia', 'Africa', 'Europe', 'South America'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which is the highest mountain peak in Africa?',
    'options': [
      'Mount Kenya',
      'Mount Kilimanjaro',
      'Table Mountain',
      'Atlas Mountains',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Argentina?',
    'options': ['Rio de Janeiro', 'Buenos Aires', 'Santiago', 'Montevideo'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which sea lies between Europe and Africa in the Mediterranean region?',
    'options': ['Red Sea', 'Mediterranean Sea', 'Black Sea', 'Adriatic Sea'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which country is known as the "Land of Fire and Ice"?',
    'options': ['Norway', 'Iceland', 'Greenland', 'Finland'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Thailand?',
    'options': ['Phuket', 'Bangkok', 'Chiang Mai', 'Pattaya'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which river flows through Paris?',
    'options': ['Rhine', 'Seine', 'Loire', 'Rhone'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which is the second largest country in the world by area?',
    'options': ['USA', 'China', 'Canada', 'Brazil'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Turkey?',
    'options': ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which US state is the largest by area?',
    'options': ['Texas', 'California', 'Alaska', 'Montana'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which Indian city is known as the "Silicon Valley of India"?',
    'options': ['Hyderabad', 'Bangalore', 'Pune', 'Chennai'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question':
        'What is the capital of South Africa (executive/administrative capital)?',
    'options': ['Cape Town', 'Johannesburg', 'Pretoria', 'Durban'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which ocean is the smallest in the world?',
    'options': [
      'Indian Ocean',
      'Atlantic Ocean',
      'Arctic Ocean',
      'Southern Ocean',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Indonesia?',
    'options': ['Bali', 'Jakarta', 'Surabaya', 'Bandung'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which African country was formerly known as Abyssinia?',
    'options': ['Kenya', 'Ethiopia', 'Sudan', 'Somalia'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of the Netherlands?',
    'options': ['Rotterdam', 'The Hague', 'Amsterdam', 'Utrecht'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which country has the most pyramids in the world?',
    'options': ['Egypt', 'Mexico', 'Sudan', 'Peru'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Geography',
    'question': 'Which is the largest state in India by area?',
    'options': ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Uttar Pradesh'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Greece?',
    'options': ['Thessaloniki', 'Athens', 'Sparta', 'Corinth'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which bay separates India from Southeast Asia?',
    'options': [
      'Bay of Bengal',
      'Arabian Sea',
      'Gulf of Mannar',
      'Andaman Sea',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Portugal?',
    'options': ['Porto', 'Lisbon', 'Faro', 'Braga'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'Which mountain range includes Mount Everest?',
    'options': ['Andes', 'Alps', 'Himalayas', 'Rockies'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Geography',
    'question': 'Which country is the largest producer of coffee in the world?',
    'options': ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question': 'What is the capital of Vietnam?',
    'options': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hue'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Geography',
    'question':
        'Which Indian union territory is an island group in the Bay of Bengal?',
    'options': [
      'Lakshadweep',
      'Andaman and Nicobar Islands',
      'Daman and Diu',
      'Puducherry',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },

  // ================= SPORTS (30) =================
  {
    'category': 'Sports',
    'question': 'Which sport is known as "the gentleman\'s game"?',
    'options': ['Golf', 'Cricket', 'Tennis', 'Chess'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'How many points is a touchdown worth in American football (before extra point)?',
    'options': ['3', '6', '7', '8'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country is famous for inventing the sport of kabaddi?',
    'options': ['Pakistan', 'India', 'Bangladesh', 'Sri Lanka'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'How many players are on a rugby union team on the field?',
    'options': ['13', '15', '17', '11'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which sport is played at Wimbledon?',
    'options': ['Golf', 'Tennis', 'Cricket', 'Badminton'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'What is the term for scoring zero runs in cricket?',
    'options': ['Duck', 'Golden goose', 'Zero run', 'Blank'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which country has won the most Olympic gold medals overall (as of recent games)?',
    'options': ['China', 'Russia', 'USA', 'Germany'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'In which sport do players use a shuttlecock?',
    'options': ['Tennis', 'Badminton', 'Squash', 'Table Tennis'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'How many players are on a field hockey team on the field?',
    'options': ['9', '11', '13', '7'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which Formula 1 driver has won the most world championships?',
    'options': [
      'Michael Schumacher',
      'Lewis Hamilton',
      'Both tied at 7',
      'Sebastian Vettel',
    ],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'What is the term for a score of one under par in golf?',
    'options': ['Bogey', 'Birdie', 'Eagle', 'Albatross'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country hosted the first modern Olympic Games in 1896?',
    'options': ['France', 'Greece', 'Italy', 'England'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'How many sets does a men\'s Grand Slam tennis final typically require to win (best of)?',
    'options': ['Best of 3', 'Best of 5', 'Best of 7', 'Single set'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which Indian cricketer is known for captaining India to the 2011 World Cup win?',
    'options': ['Sourav Ganguly', 'MS Dhoni', 'Virat Kohli', 'Rahul Dravid'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'What is the maximum break possible in a single visit in snooker?',
    'options': ['147', '155', '180', '100'],
    'correctAnswerIndex': 0,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question': 'Which sport features the "Tour de France"?',
    'options': ['Running', 'Cycling', 'Swimming', 'Triathlon'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'How many quarters are there in a standard basketball game?',
    'options': ['2', '3', '4', '5'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question': 'Which martial art originated in Japan and means "gentle way"?',
    'options': ['Karate', 'Judo', 'Taekwondo', 'Kung Fu'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which swimmer has won the most Olympic gold medals of all time?',
    'options': ['Mark Spitz', 'Michael Phelps', 'Ian Thorpe', 'Katie Ledecky'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term for a perfect score in ten-pin bowling for one frame?',
    'options': ['Spare', 'Strike', 'Split', 'Turkey'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question':
        'Which country is the traditional powerhouse of field hockey, winning many Olympic golds historically?',
    'options': ['Pakistan', 'India', 'Netherlands', 'Germany'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'What is the standard length of a marathon race?',
    'options': ['21.1 km', '42.2 km', '50 km', '30 km'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which sport uses the terms "birdie," "eagle," and "bogey"?',
    'options': ['Tennis', 'Golf', 'Cricket', 'Baseball'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are on a baseball team on the field defensively?',
    'options': ['7', '8', '9', '10'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'Which country won the UEFA Euro 2020 football championship (played in 2021)?',
    'options': ['England', 'Italy', 'Spain', 'France'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Sports',
    'question':
        'What is the term used for a tie in cricket where both teams score equal runs?',
    'options': ['Draw', 'Tie', 'Deadlock', 'Stalemate'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country is home to the sport of Sumo wrestling?',
    'options': ['China', 'Japan', 'South Korea', 'Thailand'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'How many players are there in a doubles tennis match in total?',
    'options': ['2', '3', '4', '6'],
    'correctAnswerIndex': 2,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Sports',
    'question':
        'Which trophy is awarded to the winner of the Cricket World Cup?',
    'options': [
      'The Ashes',
      'ICC Cricket World Cup Trophy',
      'Champions Trophy',
      'World Test Championship Mace',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Sports',
    'question': 'Which country has hosted the Summer Olympics the most times?',
    'options': ['France', 'USA', 'United Kingdom', 'Germany'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },

  // ================= ENTERTAINMENT (30) =================
  {
    'category': 'Entertainment',
    'question': 'Which movie franchise features the character "James Bond"?',
    'options': ['Mission Impossible', '007', 'Bourne', 'Kingsman'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Who is the composer known for the "Piano Man" song?',
    'options': [
      'Elton John',
      'Billy Joel',
      'Paul McCartney',
      'Bruce Springsteen',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which animated movie features a snowman named Olaf?',
    'options': ['Frozen', 'Ice Age', 'Happy Feet', 'Rise of the Guardians'],
    'correctAnswerIndex': 0,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Who directed the "Dark Knight" Batman trilogy?',
    'options': [
      'Zack Snyder',
      'Christopher Nolan',
      'Tim Burton',
      'Matt Reeves',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which Indian actor is known as the "Shahenshah of Bollywood"?',
    'options': ['Dilip Kumar', 'Amitabh Bachchan', 'Raj Kapoor', 'Dev Anand'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional continent in "Game of Thrones"?',
    'options': ['Middle Earth', 'Westeros', 'Narnia', 'Panem'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which singer released the album "Thriller"?',
    'options': [
      'Prince',
      'Michael Jackson',
      'Whitney Houston',
      'Stevie Wonder',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which movie won the Academy Award for Best Picture in 2020 (91st/92nd ceremony, a South Korean film)?',
    'options': ['1917', 'Joker', 'Parasite', 'Once Upon a Time in Hollywood'],
    'correctAnswerIndex': 2,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Which cartoon character lives in a pineapple under the sea?',
    'options': [
      'Patrick Star',
      'SpongeBob SquarePants',
      'Squidward',
      'Mr. Krabs',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Who is the author of the "Percy Jackson" book series?',
    'options': [
      'Rick Riordan',
      'J.K. Rowling',
      'Suzanne Collins',
      'Cassandra Clare',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian musician composed the score for "Slumdog Millionaire"?',
    'options': ['A.R. Rahman', 'Shankar Mahadevan', 'Pritam', 'Ilaiyaraaja'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the wizarding sport played on broomsticks in Harry Potter?',
    'options': ['Wizard Ball', 'Quidditch', 'Broom Racing', 'Snitch Hunt'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which actor played the lead role in "The Matrix"?',
    'options': ['Brad Pitt', 'Keanu Reeves', 'Tom Cruise', 'Will Smith'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which YouTube-famous genre involves people reacting to videos on camera?',
    'options': ['Vlogging', 'Reaction videos', 'Unboxing', 'Tutorials'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Which movie features the quote "May the Force be with you"?',
    'options': [
      'Star Trek',
      'Star Wars',
      'Guardians of the Galaxy',
      'Interstellar',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Who is the lead singer of the band Coldplay?',
    'options': ['Chris Martin', 'Bono', 'Adam Levine', 'Dave Grohl'],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian film industry is often referred to as "Tollywood"?',
    'options': [
      'Tamil film industry',
      'Telugu film industry',
      'Bengali film industry',
      'Punjabi film industry',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which movie series features a boy wizard fighting Lord Voldemort?',
    'options': [
      'Percy Jackson',
      'Harry Potter',
      'Narnia',
      'His Dark Materials',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'What is the name of the fictional city where Batman operates?',
    'options': ['Metropolis', 'Gotham City', 'Star City', 'Central City'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
  {
    'category': 'Entertainment',
    'question': 'Which actress voiced Elsa in Disney\'s "Frozen"?',
    'options': ['Kristen Bell', 'Idina Menzel', 'Emma Watson', 'Anna Kendrick'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which video game features the character "Link" and the land of Hyrule?',
    'options': [
      'Final Fantasy',
      'The Legend of Zelda',
      'Kingdom Hearts',
      'Fire Emblem',
    ],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Who is known for playing the character "Jon Snow" in Game of Thrones?',
    'options': [
      'Kit Harington',
      'Peter Dinklage',
      'Richard Madden',
      'Alfie Allen',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which is the best-selling video game of all time (as of recent data)?',
    'options': ['Tetris', 'Minecraft', 'Grand Theft Auto V', 'Wii Sports'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Bollywood actress is known as the "Chak De Girl" for her role in the movie of the same name?',
    'options': [
      'Priyanka Chopra',
      'Katrina Kaif',
      'Deepika Padukone',
      'Kareena Kapoor',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which composer is famous for the "Für Elise" piano piece?',
    'options': ['Mozart', 'Bach', 'Beethoven', 'Chopin'],
    'correctAnswerIndex': 2,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question': 'Which streaming service is known for the show "The Crown"?',
    'options': ['Amazon Prime', 'Netflix', 'Apple TV+', 'Hulu'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'What is the name of the fictional ring in "The Lord of the Rings" sought by Sauron?',
    'options': [
      'The One Ring',
      'The Elven Ring',
      'The Dwarven Ring',
      'The Ring of Power (only)',
    ],
    'correctAnswerIndex': 0,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which Indian playback singer is known for songs in "Barfi" and many Bollywood hits, often working with composer Pritam?',
    'options': ['Arijit Singh', 'Mohit Chauhan', 'Sonu Nigam', 'Shaan'],
    'correctAnswerIndex': 1,
    'difficulty': 3,
    'coins': 20,
  },
  {
    'category': 'Entertainment',
    'question': 'Which movie is famous for the line "I\'ll be back"?',
    'options': ['Rambo', 'The Terminator', 'Predator', 'RoboCop'],
    'correctAnswerIndex': 1,
    'difficulty': 2,
    'coins': 15,
  },
  {
    'category': 'Entertainment',
    'question':
        'Which app is primarily known for short-form vertical videos and viral dance trends?',
    'options': ['Instagram', 'TikTok', 'Snapchat', 'Twitter'],
    'correctAnswerIndex': 1,
    'difficulty': 1,
    'coins': 10,
  },
];
